//    CANAPE Network Testing Tool
//    Copyright (C) 2014 Context Information Security
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CANAPE.Scripting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CANAPE.Scripting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find type derived from IRunScript to execute.
        /// </summary>
        internal static string AssemblyScriptEngine_MissingRunType {
            get {
                return ResourceManager.GetString("AssemblyScriptEngine_MissingRunType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid config passed for {0} class, using existing value.
        /// </summary>
        internal static string BasePipelineNodeWithPersist_InvalidConfig {
            get {
                return ResourceManager.GetString("BasePipelineNodeWithPersist_InvalidConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get file location of assembly &apos;{0}&apos;.
        /// </summary>
        internal static string DotNetScriptEngine_CannotGetAssemblyLocation {
            get {
                return ResourceManager.GetString("DotNetScriptEngine_CannotGetAssemblyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during compile {0}.
        /// </summary>
        internal static string DotNetScriptEngine_CompileException {
            get {
                return ResourceManager.GetString("DotNetScriptEngine_CompileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting display string &apos;{0}&apos;.
        /// </summary>
        internal static string DynamicDataKey_ErrorGettingDisplayString {
            get {
                return ResourceManager.GetString("DynamicDataKey_ErrorGettingDisplayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object state is not serializable.
        /// </summary>
        internal static string DynamicDataKey_StateNotSerializable {
            get {
                return ResourceManager.GetString("DynamicDataKey_StateNotSerializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create type &apos;{0}&apos; for &apos;{1}&apos;.
        /// </summary>
        internal static string DynamicNodeFactory_CannotCreateType {
            get {
                return ResourceManager.GetString("DynamicNodeFactory_CannotCreateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid dynamic node type &apos;{0}&apos; for &apos;{1}&apos;.
        /// </summary>
        internal static string DynamicNodeFactory_InvalidNodeType {
            get {
                return ResourceManager.GetString("DynamicNodeFactory_InvalidNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a dynamic class name for &apos;{0}&apos;.
        /// </summary>
        internal static string DynamicNodeFactory_MustSpecifyClassName {
            get {
                return ResourceManager.GetString("DynamicNodeFactory_MustSpecifyClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No script specified for &apos;{0}&apos;.
        /// </summary>
        internal static string DynamicNodeFactory_NoScriptSpecified {
            get {
                return ResourceManager.GetString("DynamicNodeFactory_NoScriptSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available class for invoke.
        /// </summary>
        internal static string PythonScriptEngine_NoClassForInvoke {
            get {
                return ResourceManager.GetString("PythonScriptEngine_NoClassForInvoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Scripting_Error {
            get {
                return ResourceManager.GetString("Scripting_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create instance of object.
        /// </summary>
        internal static string Scripting_FailedToCreateInstance {
            get {
                return ResourceManager.GetString("Scripting_FailedToCreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FatalError.
        /// </summary>
        internal static string Scripting_FatalError {
            get {
                return ResourceManager.GetString("Scripting_FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Scripting_Warning {
            get {
                return ResourceManager.GetString("Scripting_Warning", resourceCulture);
            }
        }
    }
}
