//    CANAPE Network Testing Tool
//    Copyright (C) 2014 Context Information Security
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CANAPE.Security.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CANAPE.Security.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All X509Extensions should contain encoded data.
        /// </summary>
        internal static string CreateCert_NeedEncodedData {
            get {
                return ResourceManager.GetString("CreateCert_NeedEncodedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing certificate does not have a valid private key.
        /// </summary>
        internal static string CreateCert_NoPrivateKey {
            get {
                return ResourceManager.GetString("CreateCert_NoPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type must derive from ICredentialObject interface.
        /// </summary>
        internal static string CredentialsManagerService_TypeMustDeriveFromICredentialObject {
            get {
                return ResourceManager.GetString("CredentialsManagerService_TypeMustDeriveFromICredentialObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate should have a private key.
        /// </summary>
        internal static string LoadCert_NeedPrivateKey {
            get {
                return ResourceManager.GetString("LoadCert_NeedPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid OpenSSL style certificate.
        /// </summary>
        internal static string LoadCertFromOpenSslFile_InvalidOpenSslCert {
            get {
                return ResourceManager.GetString("LoadCertFromOpenSslFile_InvalidOpenSslCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not decrypt key file, check the password is correct.
        /// </summary>
        internal static string LoadRsaKeyFromFile_CannotDecryptKey {
            get {
                return ResourceManager.GetString("LoadRsaKeyFromFile_CannotDecryptKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed sequence in RSA private key.
        /// </summary>
        internal static string LoadRsaKeyFromFile_MalformedSequence {
            get {
                return ResourceManager.GetString("LoadRsaKeyFromFile_MalformedSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hash algorithm for certificate.
        /// </summary>
        internal static string NativeCertificateBuilder_InvalidHashAlgorithm {
            get {
                return ResourceManager.GetString("NativeCertificateBuilder_InvalidHashAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a cert with a private key.
        /// </summary>
        internal static string ReloadProtectedPrivateKey_NotPrivateKeyInCert {
            get {
                return ResourceManager.GetString("ReloadProtectedPrivateKey_NotPrivateKeyInCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only supports RSA crypto provider keys.
        /// </summary>
        internal static string ReloadProtectedPrivateKey_OnlySupportRSA {
            get {
                return ResourceManager.GetString("ReloadProtectedPrivateKey_OnlySupportRSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide a realm for the principal.
        /// </summary>
        internal static string SecurityPrincipal_MustProvideRealm {
            get {
                return ResourceManager.GetString("SecurityPrincipal_MustProvideRealm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide a type for the principal.
        /// </summary>
        internal static string SecurityPrincipal_MustProvideType {
            get {
                return ResourceManager.GetString("SecurityPrincipal_MustProvideType", resourceCulture);
            }
        }
    }
}
