//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CANAPE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CANAPE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon CANAPE {
            get {
                object obj = ResourceManager.GetObject("CANAPE", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to clear the project history?.
        /// </summary>
        internal static string ConfigurationForm_ClearHistory {
            get {
                return ResourceManager.GetString("ConfigurationForm_ClearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear History?.
        /// </summary>
        internal static string ConfigurationForm_ClearHistoryCaption {
            get {
                return ResourceManager.GetString("ConfigurationForm_ClearHistoryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string ConfigurationForm_DefaultLanguage {
            get {
                return ResourceManager.GetString("ConfigurationForm_DefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string ConfigurationForm_DefaultScriptConfig {
            get {
                return ResourceManager.GetString("ConfigurationForm_DefaultScriptConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must restart CANAPE to change the user interface language.
        /// </summary>
        internal static string ConfigurationForm_MustRestartToChangeLanguage {
            get {
                return ResourceManager.GetString("ConfigurationForm_MustRestartToChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Changed.
        /// </summary>
        internal static string ConfigurationForm_MustRestartToChangeLanguageCaption {
            get {
                return ResourceManager.GetString("ConfigurationForm_MustRestartToChangeLanguageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reset all settings to their defaults?.
        /// </summary>
        internal static string ConfigurationForm_ResetToDefaults {
            get {
                return ResourceManager.GetString("ConfigurationForm_ResetToDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Defaults?.
        /// </summary>
        internal static string ConfigurationForm_ResetToDefaultsCaption {
            get {
                return ResourceManager.GetString("ConfigurationForm_ResetToDefaultsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFX Certificate (*.pfx;*.p12)|*.pfx;*.p12|Certificate Files (*.cer,*.pem,*.crt)|*.cer;*.pem;*.crt|All Files (*.*)|*.*.
        /// </summary>
        internal static string CreateCert_SaveFilter {
            get {
                return ResourceManager.GetString("CreateCert_SaveFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No editor available for &apos;{0}&apos;.
        /// </summary>
        internal static string DocumentForm_NoRegisteredEditor {
            get {
                return ResourceManager.GetString("DocumentForm_NoRegisteredEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemblies (*.dll;*.exe)|*.dll;*.exe|All Files (*.*)|*.*.
        /// </summary>
        internal static string ExtensionManagerForm_AssemblyFilter {
            get {
                return ResourceManager.GetString("ExtensionManagerForm_AssemblyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create extension directory..
        /// </summary>
        internal static string ExtensionManagerForm_CouldntCreateExtensionDir {
            get {
                return ResourceManager.GetString("ExtensionManagerForm_CouldntCreateExtensionDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error.
        /// </summary>
        internal static string FatalError_Caption {
            get {
                return ResourceManager.GetString("FatalError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, a Fatal Error occurred.
        ///Please send the file {0} to the developer to help diagnose the issue.
        ///Exiting.
        /// </summary>
        internal static string FatalError_Message {
            get {
                return ResourceManager.GetString("FatalError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon FloppyDisk {
            get {
                object obj = ResourceManager.GetObject("FloppyDisk", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon folderopen {
            get {
                object obj = ResourceManager.GetObject("folderopen", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} This might not open correctly. Do you want to continue to load?.
        /// </summary>
        internal static string LoadProject_OpenAnyway {
            get {
                return ResourceManager.GetString("LoadProject_OpenAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Anyway?.
        /// </summary>
        internal static string LoadProject_OpenAnywayCaption {
            get {
                return ResourceManager.GetString("LoadProject_OpenAnywayCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: There was a security issue loading this projects &apos;{0}&apos;.\r\nCANAPE can contain dangerous resources such as fully privileged scripts which could compromise your computer. DO NOT open untrusted projects!!!! Do you want to reload insecurely?.
        /// </summary>
        internal static string LoadProject_SecurityWarning {
            get {
                return ResourceManager.GetString("LoadProject_SecurityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Issue in Project.
        /// </summary>
        internal static string LoadProject_SecurityWarningCaption {
            get {
                return ResourceManager.GetString("LoadProject_SecurityWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Files (*.cer)|*.cer|All Files (*.*)|*.*.
        /// </summary>
        internal static string MainForm_CertSaveFilter {
            get {
                return ResourceManager.GetString("MainForm_CertSaveFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to close CANAPE?.
        /// </summary>
        internal static string MainForm_ConfirmExit {
            get {
                return ResourceManager.GetString("MainForm_ConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close?.
        /// </summary>
        internal static string MainForm_ConfirmExitCaption {
            get {
                return ResourceManager.GetString("MainForm_ConfirmExitCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new updates are available.
        /// </summary>
        internal static string MainForm_NoUpdateAvailable {
            get {
                return ResourceManager.GetString("MainForm_NoUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new updates.
        /// </summary>
        internal static string MainForm_NoUpdateAvailableCaption {
            get {
                return ResourceManager.GetString("MainForm_NoUpdateAvailableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project has been modified, do you want to save?.
        /// </summary>
        internal static string MainForm_ProjectModified {
            get {
                return ResourceManager.GetString("MainForm_ProjectModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Modified?.
        /// </summary>
        internal static string MainForm_ProjectModifiedCaption {
            get {
                return ResourceManager.GetString("MainForm_ProjectModifiedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to replace the current CANAPE Root CA? It will not be possible to recover the old certificate if you do this!.
        /// </summary>
        internal static string MainForm_ReplaceRootCA {
            get {
                return ResourceManager.GetString("MainForm_ReplaceRootCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root certificate is already installed.
        /// </summary>
        internal static string MainForm_RootCertAlreadyInstalled {
            get {
                return ResourceManager.GetString("MainForm_RootCertAlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANAPE - {0}.
        /// </summary>
        internal static string MainForm_TitleText {
            get {
                return ResourceManager.GetString("MainForm_TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occurred loading file.
        /// </summary>
        internal static string MainForm_UnknownError {
            get {
                return ResourceManager.GetString("MainForm_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Untitled).
        /// </summary>
        internal static string MainForm_UntitledFile {
            get {
                return ResourceManager.GetString("MainForm_UntitledFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MessageBiox_WarningString {
            get {
                return ResourceManager.GetString("MessageBiox_WarningString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBox_ErrorString {
            get {
                return ResourceManager.GetString("MessageBox_ErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon NetGraphIcon {
            get {
                object obj = ResourceManager.GetObject("NetGraphIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Network {
            get {
                object obj = ResourceManager.GetObject("Network", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Network_Map {
            get {
                object obj = ResourceManager.GetObject("Network_Map", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Files (*.canape)|*.canape|All Files (*.*)|*.*.
        /// </summary>
        internal static string OpenFileDialog_ProjectFilter {
            get {
                return ResourceManager.GetString("OpenFileDialog_ProjectFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to enable automatic update checking? This setting can be changed later in the program configuration..
        /// </summary>
        internal static string Program_CheckForUpdates {
            get {
                return ResourceManager.GetString("Program_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Update Check?.
        /// </summary>
        internal static string Program_CheckForUpdatesCaption {
            get {
                return ResourceManager.GetString("Program_CheckForUpdatesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create user directory &apos;{0}&apos; to store configuration data. Please ensure you have permissions to create and re-run CANAPE.
        /// </summary>
        internal static string Program_ErrorCreatingUserDirectory {
            get {
                return ResourceManager.GetString("Program_ErrorCreatingUserDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: CANAPE projects can contain dangerous resources such as fully privileged scripts which could compromise your computer. DO NOT open untrusted projects!!!!.
        /// </summary>
        internal static string Program_SecurityWarning {
            get {
                return ResourceManager.GetString("Program_SecurityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big Scary Warning!.
        /// </summary>
        internal static string Program_SecurityWarningCaption {
            get {
                return ResourceManager.GetString("Program_SecurityWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ProjectIcon {
            get {
                object obj = ResourceManager.GetObject("ProjectIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PythonScriptIcon {
            get {
                object obj = ResourceManager.GetObject("PythonScriptIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon RunIcon {
            get {
                object obj = ResourceManager.GetObject("RunIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading from {0}.
        /// </summary>
        internal static string SavingLoadingForm_Loading {
            get {
                return ResourceManager.GetString("SavingLoadingForm_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving to {0}.
        /// </summary>
        internal static string SavingLoadingForm_Saving {
            get {
                return ResourceManager.GetString("SavingLoadingForm_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select previous file to open.
        /// </summary>
        internal static string StartupForm_SelectPreviousItem {
            get {
                return ResourceManager.GetString("StartupForm_SelectPreviousItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        internal static string StartupForm_SelectPreviousItemCaption {
            get {
                return ResourceManager.GetString("StartupForm_SelectPreviousItemCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon textdoc {
            get {
                object obj = ResourceManager.GetObject("textdoc", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon TickIcon {
            get {
                object obj = ResourceManager.GetObject("TickIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon UtilityText {
            get {
                object obj = ResourceManager.GetObject("UtilityText", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
