//    CANAPE Network Testing Tool
//    Copyright (C) 2014 Context Information Security
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CANAPE.Documents.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CANAPE.Documents.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associated text comment for node.
        /// </summary>
        internal static string BaseNodeConfig_CommentDescription {
            get {
                return ResourceManager.GetString("BaseNodeConfig_CommentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If True then this node handles data, otherwise it is passed automatically to the next node in the chain.
        /// </summary>
        internal static string BaseNodeConfig_EnabledDescription {
            get {
                return ResourceManager.GetString("BaseNodeConfig_EnabledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data frame filter list.
        /// </summary>
        internal static string BaseNodeConfig_FiltersDescription {
            get {
                return ResourceManager.GetString("BaseNodeConfig_FiltersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if this node should be hidden from most viewers.
        /// </summary>
        internal static string BaseNodeConfig_HiddenDescription {
            get {
                return ResourceManager.GetString("BaseNodeConfig_HiddenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textual name of the node.
        /// </summary>
        internal static string BaseNodeConfig_LabelDescription {
            get {
                return ResourceManager.GetString("BaseNodeConfig_LabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies all input packets should be logged, useful for debugging purposes.
        /// </summary>
        internal static string BaseNodeConfig_LogInputDescription {
            get {
                return ResourceManager.GetString("BaseNodeConfig_LogInputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies all output packets should be logged, useful for debugging purposes.
        /// </summary>
        internal static string BaseNodeConfig_LogOutputDescription {
            get {
                return ResourceManager.GetString("BaseNodeConfig_LogOutputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If True all the filters in the list must match for the node to handle the data.
        /// </summary>
        internal static string BaseNodeConfig_MatchAllFiltersDescription {
            get {
                return ResourceManager.GetString("BaseNodeConfig_MatchAllFiltersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textual key/value pairs to provide arbitrary values to the node.
        /// </summary>
        internal static string BaseNodeConfig_PropertiesDescription {
            get {
                return ResourceManager.GetString("BaseNodeConfig_PropertiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path in incoming frames on which you want this node to act (/ indicates the entire frame).
        /// </summary>
        internal static string BaseNodeConfig_SelectionPathDescription {
            get {
                return ResourceManager.GetString("BaseNodeConfig_SelectionPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Document.
        /// </summary>
        internal static string BinaryDocument_DefaultName {
            get {
                return ResourceManager.GetString("BinaryDocument_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set the default proxy client to the default factory.
        /// </summary>
        internal static string CANAPEProject_InvalidDefaultProxy {
            get {
                return ResourceManager.GetString("CANAPEProject_InvalidDefaultProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of project ({0}) is older than the current version of CANAPE ({1}).
        /// </summary>
        internal static string CANAPEProject_InvalidVersion {
            get {
                return ResourceManager.GetString("CANAPEProject_InvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No version information in CANAPE project.
        /// </summary>
        internal static string CANAPEProject_NoVersion {
            get {
                return ResourceManager.GetString("CANAPEProject_NoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of project ({0}) is older than the current version of CANAPE ({1}).
        /// </summary>
        internal static string CANAPEProject_OlderVersion {
            get {
                return ResourceManager.GetString("CANAPEProject_OlderVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path name to send the frame if filters match.
        /// </summary>
        internal static string DecisionNodeConfig_PathNameDescription {
            get {
                return ResourceManager.GetString("DecisionNodeConfig_PathNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a packet delay in milli-seconds.
        /// </summary>
        internal static string DelayNodeConfig_PacketDelayMsDescription {
            get {
                return ResourceManager.GetString("DelayNodeConfig_PacketDelayMsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet delay must be greater or equal to 0.
        /// </summary>
        internal static string DirectNode_InvalidPacketDelay {
            get {
                return ResourceManager.GetString("DirectNode_InvalidPacketDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full type name of the class implementing this node.
        /// </summary>
        internal static string DynamicNodeConfig_ClassNameDescription {
            get {
                return ResourceManager.GetString("DynamicNodeConfig_ClassNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script container to use for this node.
        /// </summary>
        internal static string DynamicNodeConfig_ScriptDescription {
            get {
                return ResourceManager.GetString("DynamicNodeConfig_ScriptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The colour to show in the edit window.
        /// </summary>
        internal static string EditPacketNodeConfig_ColorDescription {
            get {
                return ResourceManager.GetString("EditPacketNodeConfig_ColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The textual tag to show in an edit window.
        /// </summary>
        internal static string EditPacketNodeConfig_TagDescription {
            get {
                return ResourceManager.GetString("EditPacketNodeConfig_TagDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating fixed proxy .
        /// </summary>
        internal static string FixedProxyDocument_ErrorCreatingService {
            get {
                return ResourceManager.GetString("FixedProxyDocument_ErrorCreatingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide a valid local port.
        /// </summary>
        internal static string FixedProxyDocument_MustProvideValidLocalPort {
            get {
                return ResourceManager.GetString("FixedProxyDocument_MustProvideValidLocalPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide a valid port.
        /// </summary>
        internal static string FixedProxyDocument_MustProvideValidPort {
            get {
                return ResourceManager.GetString("FixedProxyDocument_MustProvideValidPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} Fixed Proxy listening on port {2} going to {3}:{4}.
        /// </summary>
        internal static string FixedProxyDocument_ToString {
            get {
                return ResourceManager.GetString("FixedProxyDocument_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating network service.
        /// </summary>
        internal static string GenericProxyDocument_ErrorCreatingService {
            get {
                return ResourceManager.GetString("GenericProxyDocument_ErrorCreatingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide a valid local TCP port.
        /// </summary>
        internal static string GenericProxyDocument_MustSpecifyAValidPort {
            get {
                return ResourceManager.GetString("GenericProxyDocument_MustSpecifyAValidPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A layer which implements a HTTP request and response parser.
        /// </summary>
        internal static string HttpNetworkLayerFactory_Description {
            get {
                return ResourceManager.GetString("HttpNetworkLayerFactory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Network Layer.
        /// </summary>
        internal static string HttpNetworkLayerFactory_Name {
            get {
                return ResourceManager.GetString("HttpNetworkLayerFactory_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide a certificate if not auto generating SSL cert.
        /// </summary>
        internal static string HttpProxyDocument_MustProvideCertificateForSsl {
            get {
                return ResourceManager.GetString("HttpProxyDocument_MustProvideCertificateForSsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - HTTP Proxy listening on port {1}.
        /// </summary>
        internal static string HttpProxyDocument_ToString {
            get {
                return ResourceManager.GetString("HttpProxyDocument_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - HTTP Reverse Proxy listening on port {1}.
        /// </summary>
        internal static string HttpReverseProxyDocument_ToString1 {
            get {
                return ResourceManager.GetString("HttpReverseProxyDocument_ToString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port value must be between 0 (for auto-bind) to 65535 inclusive.
        /// </summary>
        internal static string IpProxyListenerFactory_InvalidPortNumber {
            get {
                return ResourceManager.GetString("IpProxyListenerFactory_InvalidPortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a graph for layer section.
        /// </summary>
        internal static string LayerSectionFilterFactory_MustSpecifyGraph {
            get {
                return ResourceManager.GetString("LayerSectionFilterFactory_MustSpecifyGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify an input node to bind to.
        /// </summary>
        internal static string LayerSectionFilterFactory_MustSpecifyInputNode {
            get {
                return ResourceManager.GetString("LayerSectionFilterFactory_MustSpecifyInputNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify an output node to bind to.
        /// </summary>
        internal static string LayerSectionFilterFactory_MustSpecifyOutputNode {
            get {
                return ResourceManager.GetString("LayerSectionFilterFactory_MustSpecifyOutputNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The netgraph to contain in this node.
        /// </summary>
        internal static string LayerSectionNodeConfig_GraphDescription {
            get {
                return ResourceManager.GetString("LayerSectionNodeConfig_GraphDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specifies that the graphs meta should be isolated.
        /// </summary>
        internal static string LayerSectionNodeConfig_IsolatedGraphDescription {
            get {
                return ResourceManager.GetString("LayerSectionNodeConfig_IsolatedGraphDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of layers to instantiate.
        /// </summary>
        internal static string LayerSectionNodeConfig_LayersDescription {
            get {
                return ResourceManager.GetString("LayerSectionNodeConfig_LayersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a linked node for layer section.
        /// </summary>
        internal static string LayerSectionNodeFactory_MustSpecifyLinkedNode {
            get {
                return ResourceManager.GetString("LayerSectionNodeFactory_MustSpecifyLinkedNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the library class.
        /// </summary>
        internal static string LibraryNodeConfig_ClassNameDescription {
            get {
                return ResourceManager.GetString("LibraryNodeConfig_ClassNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color of the entry when placed into the log.
        /// </summary>
        internal static string LogPacketConfig_ColorDescription {
            get {
                return ResourceManager.GetString("LogPacketConfig_ColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If True all logged packets will be converted to a basic byte form before storage.
        /// </summary>
        internal static string LogPacketConfig_ConvertToBytesDescription {
            get {
                return ResourceManager.GetString("LogPacketConfig_ConvertToBytesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A textual description of the log entry.
        /// </summary>
        internal static string LogPacketConfig_TagDescription {
            get {
                return ResourceManager.GetString("LogPacketConfig_TagDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify maximum concurrent connections greater than 0.
        /// </summary>
        internal static string NetAutoClientDocument_InvalidConncurrentConnections {
            get {
                return ResourceManager.GetString("NetAutoClientDocument_InvalidConncurrentConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a positive timeout value.
        /// </summary>
        internal static string NetAutoClientDocument_InvalidTimeout {
            get {
                return ResourceManager.GetString("NetAutoClientDocument_InvalidTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a client to use.
        /// </summary>
        internal static string NetAutoClientDocument_NoFactory {
            get {
                return ResourceManager.GetString("NetAutoClientDocument_NoFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction of flow for the node.
        /// </summary>
        internal static string NetGraphContainerConfig_DirectionDescription {
            get {
                return ResourceManager.GetString("NetGraphContainerConfig_DirectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The netgraph to contain in this node.
        /// </summary>
        internal static string NetGraphContainerConfig_GraphDescription {
            get {
                return ResourceManager.GetString("NetGraphContainerConfig_GraphDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A container node which links with this one.
        /// </summary>
        internal static string NetGraphContainerConfig_LinkedNodeDescription {
            get {
                return ResourceManager.GetString("NetGraphContainerConfig_LinkedNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties set on the graph itself.
        /// </summary>
        internal static string NetGraphDocument_PropertiesDescription {
            get {
                return ResourceManager.GetString("NetGraphDocument_PropertiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating server.
        /// </summary>
        internal static string NetServerDocument_ErrorCreatingServer {
            get {
                return ResourceManager.GetString("NetServerDocument_ErrorCreatingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a server to run.
        /// </summary>
        internal static string NetServerDocument_MustSpecifyServer {
            get {
                return ResourceManager.GetString("NetServerDocument_MustSpecifyServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide a valid network port.
        /// </summary>
        internal static string NetServerDocument_ValidPort {
            get {
                return ResourceManager.GetString("NetServerDocument_ValidPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot setup a network listener, no supported IP protocol.
        /// </summary>
        internal static string NetServiceDocument_CannotSetupListener {
            get {
                return ResourceManager.GetString("NetServiceDocument_CannotSetupListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet Diff.
        /// </summary>
        internal static string PacketLogDiffDocument_DefaultName {
            get {
                return ResourceManager.GetString("PacketLogDiffDocument_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripted object is not a data endpoint type.
        /// </summary>
        internal static string ScriptDataEndpointFactory_InvalidType {
            get {
                return ResourceManager.GetString("ScriptDataEndpointFactory_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script container to use for this node.
        /// </summary>
        internal static string ScriptDataEndpointFactory_ScriptDescription {
            get {
                return ResourceManager.GetString("ScriptDataEndpointFactory_ScriptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find a script document called &apos;{0}&apos;.
        /// </summary>
        internal static string ScriptDocument_CannotFindDocument {
            get {
                return ResourceManager.GetString("ScriptDocument_CannotFindDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Script.
        /// </summary>
        internal static string ScriptDocument_DefaultName {
            get {
                return ResourceManager.GetString("ScriptDocument_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full type name of the class implementing this layer.
        /// </summary>
        internal static string ScriptNetworkLayerFactory_ClassNameDescription {
            get {
                return ResourceManager.GetString("ScriptNetworkLayerFactory_ClassNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A layer implemented by a dynamic script.
        /// </summary>
        internal static string ScriptNetworkLayerFactory_Description {
            get {
                return ResourceManager.GetString("ScriptNetworkLayerFactory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create INetworkLayer or IDataStreamParser type from script {0}.
        /// </summary>
        internal static string ScriptNetworkLayerFactory_InvalidType {
            get {
                return ResourceManager.GetString("ScriptNetworkLayerFactory_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripted Layer.
        /// </summary>
        internal static string ScriptNetworkLayerFactory_Name {
            get {
                return ResourceManager.GetString("ScriptNetworkLayerFactory_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script container to use for this layer.
        /// </summary>
        internal static string ScriptNetworkLayerFactory_ScriptDescription {
            get {
                return ResourceManager.GetString("ScriptNetworkLayerFactory_ScriptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class name for scripted layer &apos;{0}&apos; must be specified.
        /// </summary>
        internal static string ScriptNetworkLayerFactory_SpecifyClassName {
            get {
                return ResourceManager.GetString("ScriptNetworkLayerFactory_SpecifyClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The script for scripted layer &apos;{0}&apos; must be specified.
        /// </summary>
        internal static string ScriptNetworkLayerFactory_SpecifyScript {
            get {
                return ResourceManager.GetString("ScriptNetworkLayerFactory_SpecifyScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get PAC script object, falling back to direct connection.
        /// </summary>
        internal static string ScriptProxyFactory_CannotCreateScript {
            get {
                return ResourceManager.GetString("ScriptProxyFactory_CannotCreateScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide a classname for the test.
        /// </summary>
        internal static string ScriptTestDocument_MustProvideClassname {
            get {
                return ResourceManager.GetString("ScriptTestDocument_MustProvideClassname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The netgraph to contain in this node.
        /// </summary>
        internal static string SslLayerSectionNodeConfig_GraphDescription {
            get {
                return ResourceManager.GetString("SslLayerSectionNodeConfig_GraphDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specifies that the graphs meta should be isolated.
        /// </summary>
        internal static string SslLayerSectionNodeConfig_IsolatedGraphDescription {
            get {
                return ResourceManager.GetString("SslLayerSectionNodeConfig_IsolatedGraphDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The layer&apos;s SSL configuration.
        /// </summary>
        internal static string SslLayerSectionNodeConfig_SslConfigDescription {
            get {
                return ResourceManager.GetString("SslLayerSectionNodeConfig_SslConfigDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL Network Layer.
        /// </summary>
        internal static string SslNetworkLayerFactory_Description {
            get {
                return ResourceManager.GetString("SslNetworkLayerFactory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL Layer.
        /// </summary>
        internal static string SslNetworkLayerFactory_Name {
            get {
                return ResourceManager.GetString("SslNetworkLayerFactory_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the state is in the global scope.
        /// </summary>
        internal static string StateGraphDocument_GlobalStateDescription {
            get {
                return ResourceManager.GetString("StateGraphDocument_GlobalStateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the meta which determines this state.
        /// </summary>
        internal static string StateGraphDocument_MetaNameDescription {
            get {
                return ResourceManager.GetString("StateGraphDocument_MetaNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color of log packets.
        /// </summary>
        internal static string StateGraphEntry_ColorDescription {
            get {
                return ResourceManager.GetString("StateGraphEntry_ColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph which implements this state.
        /// </summary>
        internal static string StateGraphEntry_GraphDescription {
            get {
                return ResourceManager.GetString("StateGraphEntry_GraphDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of layers to apply to the section.
        /// </summary>
        internal static string StateGraphEntry_LayersDescription {
            get {
                return ResourceManager.GetString("StateGraphEntry_LayersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to log packets for this state.
        /// </summary>
        internal static string StateGraphEntry_LogPacketsDescription {
            get {
                return ResourceManager.GetString("StateGraphEntry_LogPacketsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure SSL for this layer.
        /// </summary>
        internal static string StateGraphEntry_SslConfigDescription {
            get {
                return ResourceManager.GetString("StateGraphEntry_SslConfigDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state name to select on.
        /// </summary>
        internal static string StateGraphEntry_StateNameDescription {
            get {
                return ResourceManager.GetString("StateGraphEntry_StateNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If true will drop packets which do not have a matching path, otherwise will send to default.
        /// </summary>
        internal static string SwitchNodeConfig_DropUnknownDescription {
            get {
                return ResourceManager.GetString("SwitchNodeConfig_DropUnknownDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the mechanism used to match the correct path.
        /// </summary>
        internal static string SwitchNodeConfig_ModeDescription {
            get {
                return ResourceManager.GetString("SwitchNodeConfig_ModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Document.
        /// </summary>
        internal static string TextDocument_DefaultName {
            get {
                return ResourceManager.GetString("TextDocument_DefaultName", resourceCulture);
            }
        }
    }
}
