//    CANAPE Network Testing Tool
//    Copyright (C) 2014 Context Information Security
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CANAPE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CANAPE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating node {0} - {1}.
        /// </summary>
        internal static string BaseNodeFactory_Create {
            get {
                return ResourceManager.GetString("BaseNodeFactory_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching binary data.
        /// </summary>
        internal static string BinaryDataFrameFilterFactory_MatchDescription {
            get {
                return ResourceManager.GetString("BinaryDataFrameFilterFactory_MatchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid color string format, should be a hex string in form of #RRGGBB or an X11 color name.
        /// </summary>
        internal static string ColorValue_InvalidStringFormat {
            get {
                return ResourceManager.GetString("ColorValue_InvalidStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set current node to be one from another frame.
        /// </summary>
        internal static string DataFrame_Exception1 {
            get {
                return ResourceManager.GetString("DataFrame_Exception1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} filter(s).
        /// </summary>
        internal static string DataFrameFilterExpression_ToString {
            get {
                return ResourceManager.GetString("DataFrameFilterExpression_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If True then this filter is enabled.
        /// </summary>
        internal static string DataFrameFilterFactory_EnabledDescription {
            get {
                return ResourceManager.GetString("DataFrameFilterFactory_EnabledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert the match.
        /// </summary>
        internal static string DataFrameFilterFactory_InvertDescription {
            get {
                return ResourceManager.GetString("DataFrameFilterFactory_InvertDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data frame path to select on, set to / to match the entire packet.
        /// </summary>
        internal static string DataFrameFilterFactory_PathDescription {
            get {
                return ResourceManager.GetString("DataFrameFilterFactory_PathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add a node which is attached to another frame.
        /// </summary>
        internal static string DataKey_AddSubNodeException {
            get {
                return ResourceManager.GetString("DataKey_AddSubNodeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid encoding name {0}.
        /// </summary>
        internal static string DataKey_AddValueInvalidEncoding {
            get {
                return ResourceManager.GetString("DataKey_AddValueInvalidEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The child node is not a child of this key.
        /// </summary>
        internal static string DataKey_InvalidChildNode {
            get {
                return ResourceManager.GetString("DataKey_InvalidChildNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only read between 0 and 63 bits from a stream at a time.
        /// </summary>
        internal static string DataReader_InvalidBitCount {
            get {
                return ResourceManager.GetString("DataReader_InvalidBitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid primitive type passed to ReadPrimitive - {0}.
        /// </summary>
        internal static string DataReader_InvalidPrimitiveType {
            get {
                return ResourceManager.GetString("DataReader_InvalidPrimitiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read all requested bytes.
        /// </summary>
        internal static string DataReader_ReadBytesEof {
            get {
                return ResourceManager.GetString("DataReader_ReadBytesEof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read a valid character from the stream.
        /// </summary>
        internal static string DataReader_ReadCharEof {
            get {
                return ResourceManager.GetString("DataReader_ReadCharEof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only write between 0 and 63 bits from a stream at a time.
        /// </summary>
        internal static string DataWriter_InvalidBitCount {
            get {
                return ResourceManager.GetString("DataWriter_InvalidBitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid primitive type passed to WritePrimitive - {0}.
        /// </summary>
        internal static string DataWriter_InvalidPrimitiveType {
            get {
                return ResourceManager.GetString("DataWriter_InvalidPrimitiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value name {0}.
        /// </summary>
        internal static string EnumDataValue_FindValueByName {
            get {
                return ResourceManager.GetString("EnumDataValue_FindValueByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid string for enum {0}.
        /// </summary>
        internal static string EnumDataValue_FromString {
            get {
                return ResourceManager.GetString("EnumDataValue_FromString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid underlying type for enumeration.
        /// </summary>
        internal static string EnumDataValue_InvalidType {
            get {
                return ResourceManager.GetString("EnumDataValue_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid escape sequence encountered.
        /// </summary>
        internal static string GeneralUtils_DecodeEscapedInvalidEscape {
            get {
                return ResourceManager.GetString("GeneralUtils_DecodeEscapedInvalidEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid trailing backslash in escaped string.
        /// </summary>
        internal static string GeneralUtils_DecodeEscapedStringTrailingSlash {
            get {
                return ResourceManager.GetString("GeneralUtils_DecodeEscapedStringTrailingSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown string escape sequence {0}.
        /// </summary>
        internal static string GeneralUtils_DecodeEscapedStringUnknownEscape {
            get {
                return ResourceManager.GetString("GeneralUtils_DecodeEscapedStringUnknownEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String must only contain bytes in hex or spaces.
        /// </summary>
        internal static string GeneralUtils_InvalidHexString {
            get {
                return ResourceManager.GetString("GeneralUtils_InvalidHexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex string must be a multiple of 2 hex characters.
        /// </summary>
        internal static string GeneralUtils_InvalidHexStringLength {
            get {
                return ResourceManager.GetString("GeneralUtils_InvalidHexStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid underlying type for value.
        /// </summary>
        internal static string GenericDataValue_InvalidType {
            get {
                return ResourceManager.GetString("GenericDataValue_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating user config directory.
        /// </summary>
        internal static string GetConfigDir_ErrorCreatingDir {
            get {
                return ResourceManager.GetString("GetConfigDir_ErrorCreatingDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object passed to CompareTo not a Int24.
        /// </summary>
        internal static string Int24_InvalidCompareObject {
            get {
                return ResourceManager.GetString("Int24_InvalidCompareObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find DataNode {0}.
        /// </summary>
        internal static string MissingDataNodeException_DefaultMessage {
            get {
                return ResourceManager.GetString("MissingDataNodeException_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid endpoint ID {0}.
        /// </summary>
        internal static string NetGraph_InvalidEndpointId {
            get {
                return ResourceManager.GetString("NetGraph_InvalidEndpointId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A graph must be specified for container.
        /// </summary>
        internal static string NetGraphContainerFactory_MustSpecifyGraph {
            get {
                return ResourceManager.GetString("NetGraphContainerFactory_MustSpecifyGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subgraph must have a client and server node.
        /// </summary>
        internal static string NetGraphContainerNode_InvalidGraph {
            get {
                return ResourceManager.GetString("NetGraphContainerNode_InvalidGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have a client endpoint to go from client to server.
        /// </summary>
        internal static string NetGraphFactory_NoClientEndpoint {
            get {
                return ResourceManager.GetString("NetGraphFactory_NoClientEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have a server endpoint to go from server to client.
        /// </summary>
        internal static string NetGraphFactory_NoServerEndpoint {
            get {
                return ResourceManager.GetString("NetGraphFactory_NoServerEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of selected nodes to test against.
        /// </summary>
        internal static string NodeCountDataFrameFilterFactory_CountDescription {
            get {
                return ResourceManager.GetString("NodeCountDataFrameFilterFactory_CountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} selected nodes.
        /// </summary>
        internal static string NodeCountDataFrameFilterFactory_DisplayString {
            get {
                return ResourceManager.GetString("NodeCountDataFrameFilterFactory_DisplayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparion operation.
        /// </summary>
        internal static string NodeCountDataFrameFilterFactory_OperationDescription {
            get {
                return ResourceManager.GetString("NodeCountDataFrameFilterFactory_OperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create the abstract class {0}.
        /// </summary>
        internal static string ObjectConverter_GetObjectAbstract {
            get {
                return ResourceManager.GetString("ObjectConverter_GetObjectAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array types must be represeted by a DataKey.
        /// </summary>
        internal static string ObjectConverter_GetObjectArray {
            get {
                return ResourceManager.GetString("ObjectConverter_GetObjectArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex types must be represeted by a DataKey.
        /// </summary>
        internal static string ObjectConverter_GetObjectComplex {
            get {
                return ResourceManager.GetString("ObjectConverter_GetObjectComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create instance of type {0}.
        /// </summary>
        internal static string ObjectConverter_GetObjectCouldntCreate {
            get {
                return ResourceManager.GetString("ObjectConverter_GetObjectCouldntCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime types must be represented by a DateTimeDataValue.
        /// </summary>
        internal static string ObjectConverter_GetObjectDateTime {
            get {
                return ResourceManager.GetString("ObjectConverter_GetObjectDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerations must be either a portable enum, a primitive type or a string.
        /// </summary>
        internal static string ObjectConverter_GetObjectEnum {
            get {
                return ResourceManager.GetString("ObjectConverter_GetObjectEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primitive types must be represented by a DataValue.
        /// </summary>
        internal static string ObjectConverter_GetObjectPrimitive {
            get {
                return ResourceManager.GetString("ObjectConverter_GetObjectPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot assign instance of type {0} to {1}.
        /// </summary>
        internal static string ObjectConverter_GetTypeFromNode {
            get {
                return ResourceManager.GetString("ObjectConverter_GetTypeFromNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid magic value 0x{0:X08} for PCAP.
        /// </summary>
        internal static string PcapReader_InvalidMagic {
            get {
                return ResourceManager.GetString("PcapReader_InvalidMagic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Ethernet PCAPs are supported.
        /// </summary>
        internal static string PcapReader_OnlyEthernet {
            get {
                return ResourceManager.GetString("PcapReader_OnlyEthernet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid config passed for {0} class, using existing value.
        /// </summary>
        internal static string PersistNodeImpl_InvalidConfig {
            get {
                return ResourceManager.GetString("PersistNodeImpl_InvalidConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read out another line from the stream.
        /// </summary>
        internal static string ReadLine_CountNotReadFromStream {
            get {
                return ResourceManager.GetString("ReadLine_CountNotReadFromStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to the type of search the filter should perform to match the element.
        /// </summary>
        internal static string SetDataFrameFilterFactory_SearchModeDescription {
            get {
                return ResourceManager.GetString("SetDataFrameFilterFactory_SearchModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the match is case sensitive.
        /// </summary>
        internal static string StringDataFrameFilterFactory_CaseSensitiveDescription {
            get {
                return ResourceManager.GetString("StringDataFrameFilterFactory_CaseSensitiveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid encoding format.
        /// </summary>
        internal static string StringDataFrameFilterFactory_GetEncodigFromTypeException {
            get {
                return ResourceManager.GetString("StringDataFrameFilterFactory_GetEncodigFromTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string to match.
        /// </summary>
        internal static string StringDataFrameFilterFactory_MatchDescription {
            get {
                return ResourceManager.GetString("StringDataFrameFilterFactory_MatchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String encoding when the data is not already in a string format.
        /// </summary>
        internal static string StringDataFrameFilterFactory_StringEncodingDescription {
            get {
                return ResourceManager.GetString("StringDataFrameFilterFactory_StringEncodingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert {0} to unix time, out of range.
        /// </summary>
        internal static string ToUnixTime_CannotConvert {
            get {
                return ResourceManager.GetString("ToUnixTime_CannotConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object passed to CompareTo not a UInt24.
        /// </summary>
        internal static string UInt24_InvalidCompareObject {
            get {
                return ResourceManager.GetString("UInt24_InvalidCompareObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unix time must be 4 bytes in size.
        /// </summary>
        internal static string UnixDateTimeDataValue_OnFromArray {
            get {
                return ResourceManager.GetString("UnixDateTimeDataValue_OnFromArray", resourceCulture);
            }
        }
    }
}
