//    CANAPE Network Testing Tool
//    Copyright (C) 2014 Context Information Security
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CANAPE.Parser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CANAPE.Parser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed byte value does not match required value read &apos;{0}&apos; required &apos;{1}&apos;.
        /// </summary>
        internal static string BaseParser_CMPFailure {
            get {
                return ResourceManager.GetString("BaseParser_CMPFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid sequence choice in type {0}. Specify a default type if required.
        /// </summary>
        internal static string BaseParser_NoValidSequenceChoice {
            get {
                return ResourceManager.GetString("BaseParser_NoValidSequenceChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DataReader stream must be seekable to perform magic style sequence matching.
        /// </summary>
        internal static string BaseParser_RSCStreamCannotSeek {
            get {
                return ResourceManager.GetString("BaseParser_RSCStreamCannotSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed with expression &apos;{0}&apos;.
        /// </summary>
        internal static string BaseParser_ValidateFailed {
            get {
                return ResourceManager.GetString("BaseParser_ValidateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit field must be between 0 and 64 bits in size.
        /// </summary>
        internal static string BitField_InvalidSize {
            get {
                return ResourceManager.GetString("BitField_InvalidSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of bits if using a bit field.
        /// </summary>
        internal static string BitFieldMemberEntry_BitsDescription {
            get {
                return ResourceManager.GetString("BitFieldMemberEntry_BitsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value to use for False.
        /// </summary>
        internal static string BooleanMemberEntry_FalseValueDescription {
            get {
                return ResourceManager.GetString("BooleanMemberEntry_FalseValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot represent value {0} in a {1}.
        /// </summary>
        internal static string BooleanMemberEntry_InvalidValue {
            get {
                return ResourceManager.GetString("BooleanMemberEntry_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value to use for True.
        /// </summary>
        internal static string BooleanMemberEntry_TrueValueDescription {
            get {
                return ResourceManager.GetString("BooleanMemberEntry_TrueValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry must be a string or a primitive value.
        /// </summary>
        internal static string CalculatorMemberEntry_EntryMustBeStringOrPrimitive {
            get {
                return ResourceManager.GetString("CalculatorMemberEntry_EntryMustBeStringOrPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If true the expressions are used to read and write the member. The base type is just used as its representation..
        /// </summary>
        internal static string CalculatorMemberEntry_OnlyCalculatedDescription {
            get {
                return ResourceManager.GetString("CalculatorMemberEntry_OnlyCalculatedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression used to calculate a value on read.
        /// </summary>
        internal static string CalculatorMemberEntry_ReadExpressionDescription {
            get {
                return ResourceManager.GetString("CalculatorMemberEntry_ReadExpressionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression used to calculate a value on write.
        /// </summary>
        internal static string CalculatorMemberEntry_WriteExpressionDescription {
            get {
                return ResourceManager.GetString("CalculatorMemberEntry_WriteExpressionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encoding to use for the string.
        /// </summary>
        internal static string CharMemberEntry_StringEncodingDescription {
            get {
                return ResourceManager.GetString("CharMemberEntry_StringEncodingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The base member type.
        /// </summary>
        internal static string ContainerMemberEntry_BaseTypeDescription {
            get {
                return ResourceManager.GetString("ContainerMemberEntry_BaseTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enumeration type for this entry.
        /// </summary>
        internal static string EnumMemberEntry_EnumTypeDescription {
            get {
                return ResourceManager.GetString("EnumMemberEntry_EnumTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if this enumeration is flags or values.
        /// </summary>
        internal static string EnumParserType_IsFlagsDescription {
            get {
                return ResourceManager.GetString("EnumParserType_IsFlagsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at() function requires target and index arguments.
        /// </summary>
        internal static string ExpressionResolver_AtRequires2Arguments {
            get {
                return ResourceManager.GetString("ExpressionResolver_AtRequires2Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at() function target needs to be indexable (e.g. string or array).
        /// </summary>
        internal static string ExpressionResolver_AtTargetNeedsToBeIndexable {
            get {
                return ResourceManager.GetString("ExpressionResolver_AtTargetNeedsToBeIndexable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve property {0}.
        /// </summary>
        internal static string ExpressionResolver_CannotFindProperty {
            get {
                return ResourceManager.GetString("ExpressionResolver_CannotFindProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve function {0}.
        /// </summary>
        internal static string ExpressionResolver_CannotFuncFunction {
            get {
                return ResourceManager.GetString("ExpressionResolver_CannotFuncFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The byte data to read and write from the stream.
        /// </summary>
        internal static string FixedBytesMemberEntry_BytesDescription {
            get {
                return ResourceManager.GetString("FixedBytesMemberEntry_BytesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If true the byte data read from the stream will be validated.
        /// </summary>
        internal static string FixedBytesMemberEntry_ValidateDescription {
            get {
                return ResourceManager.GetString("FixedBytesMemberEntry_ValidateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of the fixed array in elements.
        /// </summary>
        internal static string FixedLengthGenericArrayMemberEntry_LengthDescription {
            get {
                return ResourceManager.GetString("FixedLengthGenericArrayMemberEntry_LengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether the Length field is a number of elements or number of bytes.
        /// </summary>
        internal static string FixedLengthPrimitiveArrayMemberEntry_IsByteLengthDescription {
            get {
                return ResourceManager.GetString("FixedLengthPrimitiveArrayMemberEntry_IsByteLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of the fixed array in elements.
        /// </summary>
        internal static string FixedLengthPrimitiveArrayMemberEntry_LengthDescription {
            get {
                return ResourceManager.GetString("FixedLengthPrimitiveArrayMemberEntry_LengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A string which is fixed in length.
        /// </summary>
        internal static string FixedLengthStringMemberEntry_Description {
            get {
                return ResourceManager.GetString("FixedLengthStringMemberEntry_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether the Length field is a number of elements or number of bytes.
        /// </summary>
        internal static string FixedLengthStringMemberEntry_IsByteLengthDescription {
            get {
                return ResourceManager.GetString("FixedLengthStringMemberEntry_IsByteLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the fixed string in characters units.
        /// </summary>
        internal static string FixedLengthStringMemberEntry_LengthDescription {
            get {
                return ResourceManager.GetString("FixedLengthStringMemberEntry_LengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A character to use to pad the string to the correct length if it is too short.
        /// </summary>
        internal static string FixedLengthStringMemberEntry_PaddingDescription {
            get {
                return ResourceManager.GetString("FixedLengthStringMemberEntry_PaddingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String must be greater or equal to 0 characters.
        /// </summary>
        internal static string FixedLengthStringMemberEntry_StringLengthInvalid {
            get {
                return ResourceManager.GetString("FixedLengthStringMemberEntry_StringLengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type must be a float or double.
        /// </summary>
        internal static string FloatPrimitiveMemberEntry_InvalidType {
            get {
                return ResourceManager.GetString("FloatPrimitiveMemberEntry_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the array or string. Can be a complex expression..
        /// </summary>
        internal static string Generic_LengthDescription {
            get {
                return ResourceManager.GetString("Generic_LengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expression to calculate the length instead of using the Length property.
        /// </summary>
        internal static string Generic_LengthExpressionDescription {
            get {
                return ResourceManager.GetString("Generic_LengthExpressionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies an expression which is used to calculate the length when reading the value.
        /// </summary>
        internal static string Generic_LengthReadExpressionDescription {
            get {
                return ResourceManager.GetString("Generic_LengthReadExpressionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies an expression which is used to calculate the length when writing the value.
        /// </summary>
        internal static string Generic_LengthWriteExpressionDescription {
            get {
                return ResourceManager.GetString("Generic_LengthWriteExpressionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expression which specifies how many trailing bytes are present for this member.
        /// </summary>
        internal static string Generic_TrailingLength {
            get {
                return ResourceManager.GetString("Generic_TrailingLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received exception &apos;{0}&apos; while reading type {1}.
        /// </summary>
        internal static string GenericStreamParser_ReadException {
            get {
                return ResourceManager.GetString("GenericStreamParser_ReadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received exception &apos;{0}&apos; while writing type {1}.
        /// </summary>
        internal static string GenericStreamParser_WriteException {
            get {
                return ResourceManager.GetString("GenericStreamParser_WriteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object passed to CompareTo not a Int7V.
        /// </summary>
        internal static string Int7V_InvalidCompareObject {
            get {
                return ResourceManager.GetString("Int7V_InvalidCompareObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object passed to CompareTO not an {0}.
        /// </summary>
        internal static string IntB_InvalidCompareObject {
            get {
                return ResourceManager.GetString("IntB_InvalidCompareObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type must be a primitive type.
        /// </summary>
        internal static string IntegerMemberEntry_InvalidType {
            get {
                return ResourceManager.GetString("IntegerMemberEntry_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the display format of the member.
        /// </summary>
        internal static string IntegerPrimitiveMemberEntry_FormatDescription {
            get {
                return ResourceManager.GetString("IntegerPrimitiveMemberEntry_FormatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type must be an integer type.
        /// </summary>
        internal static string IntegerPrimitiveMemberEntry_InvalidType {
            get {
                return ResourceManager.GetString("IntegerPrimitiveMemberEntry_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a textual description for this member.
        /// </summary>
        internal static string MemberEntry_DescriptionDescription {
            get {
                return ResourceManager.GetString("MemberEntry_DescriptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a guid which determines how the node should be edited and displayed.
        /// </summary>
        internal static string MemberEntry_DisplayClassDescription {
            get {
                return ResourceManager.GetString("MemberEntry_DisplayClassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set the member is not output in the final structure.
        /// </summary>
        internal static string MemberEntry_HiddenDescription {
            get {
                return ResourceManager.GetString("MemberEntry_HiddenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field reference.
        /// </summary>
        internal static string MemberEntry_InvalidFieldReference {
            get {
                return ResourceManager.GetString("MemberEntry_InvalidFieldReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &apos;{0}&apos; is not a valid identifier.
        /// </summary>
        internal static string MemberEntry_InvalidName {
            get {
                return ResourceManager.GetString("MemberEntry_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist as a reference.
        /// </summary>
        internal static string MemberEntry_InvalidReference {
            get {
                return ResourceManager.GetString("MemberEntry_InvalidReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &apos;{0}&apos; already exists in the sequence.
        /// </summary>
        internal static string MemberEntry_NameAlreadyExists {
            get {
                return ResourceManager.GetString("MemberEntry_NameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the member entry.
        /// </summary>
        internal static string MemberEntry_NameDescription {
            get {
                return ResourceManager.GetString("MemberEntry_NameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expression which is used to determine if reading or writing this member is optional.
        /// </summary>
        internal static string MemberEntry_OptionalExpressionDescription {
            get {
                return ResourceManager.GetString("MemberEntry_OptionalExpressionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set the member is read only in the final structure.
        /// </summary>
        internal static string MemberEntry_ReadOnlyDescription {
            get {
                return ResourceManager.GetString("MemberEntry_ReadOnlyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the type.
        /// </summary>
        internal static string MemberEntry_TypeNameDescription {
            get {
                return ResourceManager.GetString("MemberEntry_TypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique ID of the type.
        /// </summary>
        internal static string MemberEntry_UuidDescription {
            get {
                return ResourceManager.GetString("MemberEntry_UuidDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expression used to validate the value during parsing.
        /// </summary>
        internal static string MemberEntry_ValidateExpressionDescription {
            get {
                return ResourceManager.GetString("MemberEntry_ValidateExpressionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find member {0} in reference chain.
        /// </summary>
        internal static string MemberEntryReference_CouldNotFindMember {
            get {
                return ResourceManager.GetString("MemberEntryReference_CouldNotFindMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference chain is invalid.
        /// </summary>
        internal static string MemberEntryReference_InvalidChain {
            get {
                return ResourceManager.GetString("MemberEntryReference_InvalidChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chains must end with built-in types.
        /// </summary>
        internal static string MemberEntryReference_InvalidChainMustEndWithTypes {
            get {
                return ResourceManager.GetString("MemberEntryReference_InvalidChainMustEndWithTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chains with multiple items must start with sequences.
        /// </summary>
        internal static string MemberEntryReference_InvalidChainMustStartWithSequences {
            get {
                return ResourceManager.GetString("MemberEntryReference_InvalidChainMustStartWithSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies a custom format string for the data (overrides anything else).
        /// </summary>
        internal static string NumericPrimitiveMemberEntry_CustomFormatDescription {
            get {
                return ResourceManager.GetString("NumericPrimitiveMemberEntry_CustomFormatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The endian of the type for parsing (not applicable for bytes).
        /// </summary>
        internal static string NumericPrimitiveMemberEntry_EndianDescription {
            get {
                return ResourceManager.GetString("NumericPrimitiveMemberEntry_EndianDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a textual description for this type.
        /// </summary>
        internal static string ParserType_DescriptionDescription {
            get {
                return ResourceManager.GetString("ParserType_DescriptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a guid which determines how the node should be edited and displayed.
        /// </summary>
        internal static string ParserType_DisplayClassDescription {
            get {
                return ResourceManager.GetString("ParserType_DisplayClassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique ID of the type.
        /// </summary>
        internal static string ParserType_UuidDescription {
            get {
                return ResourceManager.GetString("ParserType_UuidDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid primitive type.
        /// </summary>
        internal static string ParserUtils_InvalidPrimitiveType {
            get {
                return ResourceManager.GetString("ParserUtils_InvalidPrimitiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the number of bytes to not read from the end (note this is _not_ primitive values).
        /// </summary>
        internal static string ReadToEndPrimitiveArrayMemberEntry_TrailingLengthDescription {
            get {
                return ResourceManager.GetString("ReadToEndPrimitiveArrayMemberEntry_TrailingLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} String (Read To End).
        /// </summary>
        internal static string ReadToEndStringMemberEntry_ToStringFormat {
            get {
                return ResourceManager.GetString("ReadToEndStringMemberEntry_ToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} String (Read To End - {1} characters).
        /// </summary>
        internal static string ReadToEndStringMemberEntry_ToStringTrailingFormat {
            get {
                return ResourceManager.GetString("ReadToEndStringMemberEntry_ToStringTrailingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This specifies the number of trailing characters to not read from the end.
        /// </summary>
        internal static string ReadToEndStringMemberEntry_TrailingLengthDescription {
            get {
                return ResourceManager.GetString("ReadToEndStringMemberEntry_TrailingLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify an adjust value for the length which is added at deserialization and subtracted and serialization.
        /// </summary>
        internal static string ReferenceLengthGenericArrayMemberEntry_AdjustmentDescription {
            get {
                return ResourceManager.GetString("ReferenceLengthGenericArrayMemberEntry_AdjustmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether the Length field is a number of elements or number of bytes.
        /// </summary>
        internal static string ReferenceLengthGenericArrayMemberEntry_IsByteLengthDescription {
            get {
                return ResourceManager.GetString("ReferenceLengthGenericArrayMemberEntry_IsByteLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define the member reference to get the length from.
        /// </summary>
        internal static string ReferenceLengthGenericArrayMemberEntry_ReferenceDescription {
            get {
                return ResourceManager.GetString("ReferenceLengthGenericArrayMemberEntry_ReferenceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify an adjust value for the length which is added at deserialization and subtracted and serialization.
        /// </summary>
        internal static string ReferenceLengthPrimitiveArrayMemberEntry_AdjustmentDescription {
            get {
                return ResourceManager.GetString("ReferenceLengthPrimitiveArrayMemberEntry_AdjustmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether the Length field is a number of elements or number of bytes.
        /// </summary>
        internal static string ReferenceLengthPrimitiveArrayMemberEntry_IsByteLengthDescription {
            get {
                return ResourceManager.GetString("ReferenceLengthPrimitiveArrayMemberEntry_IsByteLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define the member reference to get the length from.
        /// </summary>
        internal static string ReferenceLengthPrimitiveArrayMemberEntry_ReferenceDescription {
            get {
                return ResourceManager.GetString("ReferenceLengthPrimitiveArrayMemberEntry_ReferenceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify an adjust value for the length which is added at deserialization and subtracted and serialization.
        /// </summary>
        internal static string ReferenceLengthStringMemberEntry_AdjustmentDescription {
            get {
                return ResourceManager.GetString("ReferenceLengthStringMemberEntry_AdjustmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether the Length field is a number of elements or number of bytes.
        /// </summary>
        internal static string ReferenceLengthStringMemberEntry_IsByteLengthDescription {
            get {
                return ResourceManager.GetString("ReferenceLengthStringMemberEntry_IsByteLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define the member reference to get the length from.
        /// </summary>
        internal static string ReferenceLengthStringMemberEntry_ReferenceDescription {
            get {
                return ResourceManager.GetString("ReferenceLengthStringMemberEntry_ReferenceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expression which resolves to a boolean value to determine when to apply this sequence choice.
        /// </summary>
        internal static string SequenceChoice_BooleanExpressionDescription {
            get {
                return ResourceManager.GetString("SequenceChoice_BooleanExpressionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of sequence for this entry.
        /// </summary>
        internal static string SequenceChoice_SequenceTypeDescription {
            get {
                return ResourceManager.GetString("SequenceChoice_SequenceTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of sequence choices to check for.
        /// </summary>
        internal static string SequenceChoiceMemberEntry_ChoicesDescription {
            get {
                return ResourceManager.GetString("SequenceChoiceMemberEntry_ChoicesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default sequence type to apply if no other match is made.
        /// </summary>
        internal static string SequenceChoiceMemberEntry_DefaultType {
            get {
                return ResourceManager.GetString("SequenceChoiceMemberEntry_DefaultType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If true ignores the choice expressions, relies on validation rules in the sequences to determine what to structure is parsed.
        /// </summary>
        internal static string SequenceChoiceMemberEntry_MagicParserDescription {
            get {
                return ResourceManager.GetString("SequenceChoiceMemberEntry_MagicParserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to auto-populate the &apos;value&apos; parameter in an expression.
        /// </summary>
        internal static string SequenceChoiceMemberEntry_ReferenceDescription {
            get {
                return ResourceManager.GetString("SequenceChoiceMemberEntry_ReferenceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add a choice the type must be a sequence.
        /// </summary>
        internal static string SequenceChoiceMemberEntry_SequenceTypeMustBeASequence {
            get {
                return ResourceManager.GetString("SequenceChoiceMemberEntry_SequenceTypeMustBeASequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The endian of the integer type for parsing.
        /// </summary>
        internal static string SequenceParserType_DefaultEndian {
            get {
                return ResourceManager.GetString("SequenceParserType_DefaultEndian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already a member of another type.
        /// </summary>
        internal static string SequenceParserType_MemberAlreadyParented {
            get {
                return ResourceManager.GetString("SequenceParserType_MemberAlreadyParented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists as a member.
        /// </summary>
        internal static string SequenceParserType_NameExists {
            get {
                return ResourceManager.GetString("SequenceParserType_NameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided member is not part of this sequence type.
        /// </summary>
        internal static string SequenceParserType_NotOurMember {
            get {
                return ResourceManager.GetString("SequenceParserType_NotOurMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expression to run prior to data serialization.
        /// </summary>
        internal static string SequenceParserType_PreserializeExpressionDescription {
            get {
                return ResourceManager.GetString("SequenceParserType_PreserializeExpressionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If true then this sequence is considered only for internal use.
        /// </summary>
        internal static string SequenceParserType_PrivateDescription {
            get {
                return ResourceManager.GetString("SequenceParserType_PrivateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expression which represents the size of the value to parse.
        /// </summary>
        internal static string SizedMemberEntry_ReadExpressionDescription {
            get {
                return ResourceManager.GetString("SizedMemberEntry_ReadExpressionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If true then the sized entry will read to the end of the stream.
        /// </summary>
        internal static string SizedMemberEntry_ReadToEndDescription {
            get {
                return ResourceManager.GetString("SizedMemberEntry_ReadToEndDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a format string, uses a syntax similar to perl replacement, e.g. &quot;Format $var&quot; will lookup the value &apos;var&apos; and replace.
        /// </summary>
        internal static string StreamParserType_FormatStringDescription {
            get {
                return ResourceManager.GetString("StreamParserType_FormatStringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encoding to use for the string.
        /// </summary>
        internal static string StringMemberEntry_StringEncodingDescription {
            get {
                return ResourceManager.GetString("StringMemberEntry_StringEncodingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether the termination condition is required or not. If not then can also read to end of stream..
        /// </summary>
        internal static string TerminatedGenericArrayMemberEntry_RequiredDescription {
            get {
                return ResourceManager.GetString("TerminatedGenericArrayMemberEntry_RequiredDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expression which specifies the term condition. Use &apos;value&apos; for the current read element and &apos;i&apos; for the current index..
        /// </summary>
        internal static string TerminatedGenericArrayMemberEntry_TermConditionDescription {
            get {
                return ResourceManager.GetString("TerminatedGenericArrayMemberEntry_TermConditionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expression which can be used to terminate the array. The current read value is represented as &apos;value&apos;.
        /// </summary>
        internal static string TerminatedGenericArrayMemberEntry_TermExpressionDescription {
            get {
                return ResourceManager.GetString("TerminatedGenericArrayMemberEntry_TermExpressionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to true to require the terminating character or string, otherwise.
        /// </summary>
        internal static string TerminatedStringMemberEntry_RequiredDescription {
            get {
                return ResourceManager.GetString("TerminatedStringMemberEntry_RequiredDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A character to indicate the end of string.
        /// </summary>
        internal static string TerminatedStringMemberEntry_TermCharDescription {
            get {
                return ResourceManager.GetString("TerminatedStringMemberEntry_TermCharDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A string to indicate the end of string, can use basic C style escapes such as \n, \t and \0.
        /// </summary>
        internal static string TerminatedStringMemberEntry_TermStringDescription {
            get {
                return ResourceManager.GetString("TerminatedStringMemberEntry_TermStringDescription", resourceCulture);
            }
        }
    }
}
