//    CANAPE Network Testing Tool
//    Copyright (C) 2014 Context Information Security
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CANAPE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CANAPE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _112_DownArrowShort_Green {
            get {
                object obj = ResourceManager.GetObject("_112_DownArrowShort_Green", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _112_LeftArrowShort_Green {
            get {
                object obj = ResourceManager.GetObject("_112_LeftArrowShort_Green", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _112_RightArrowShort_Green {
            get {
                object obj = ResourceManager.GetObject("_112_RightArrowShort_Green", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _112_Tick_Green {
            get {
                object obj = ResourceManager.GetObject("_112_Tick_Green", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _112_UpArrowShort_Green {
            get {
                object obj = ResourceManager.GetObject("_112_UpArrowShort_Green", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify an assembly name for manual loading.
        /// </summary>
        internal static string AddReferenceForm_MustSpecifyAnAssemblyName {
            get {
                return ResourceManager.GetString("AddReferenceForm_MustSpecifyAnAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*.
        /// </summary>
        internal static string AllFilesFilter_String {
            get {
                return ResourceManager.GetString("AllFilesFilter_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Assembly_ProjectEntry {
            get {
                object obj = ResourceManager.GetObject("Assembly_ProjectEntry", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a match.
        /// </summary>
        internal static string BinaryDataEditorControl_NoMatch {
            get {
                return ResourceManager.GetString("BinaryDataEditorControl_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Match.
        /// </summary>
        internal static string BinaryDataEditorControl_NoMatchCaption {
            get {
                return ResourceManager.GetString("BinaryDataEditorControl_NoMatchCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building differences!.
        /// </summary>
        internal static string BinaryFrameDiffControl_BuildingDifferences {
            get {
                return ResourceManager.GetString("BinaryFrameDiffControl_BuildingDifferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference {0} of {1}.
        /// </summary>
        internal static string BinaryFrameDiffControl_LabelFormat {
            get {
                return ResourceManager.GetString("BinaryFrameDiffControl_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No differences found.
        /// </summary>
        internal static string BinaryFrameDiffControl_NoDifferenceFound {
            get {
                return ResourceManager.GetString("BinaryFrameDiffControl_NoDifferenceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Differences.
        /// </summary>
        internal static string BinaryFrameDiffControl_NoDifferenceFoundCaption {
            get {
                return ResourceManager.GetString("BinaryFrameDiffControl_NoDifferenceFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you to specify an empty tag?.
        /// </summary>
        internal static string ChangeTagForm_UseEmptyTag {
            get {
                return ResourceManager.GetString("ChangeTagForm_UseEmptyTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Tag?.
        /// </summary>
        internal static string ChangeTagForm_UseEmptyTagCaption {
            get {
                return ResourceManager.GetString("ChangeTagForm_UseEmptyTagCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a directory which exists.
        /// </summary>
        internal static string CloneCertChainForm_DestinationMustBeADirectoryAndExist {
            get {
                return ResourceManager.GetString("CloneCertChainForm_DestinationMustBeADirectoryAndExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url scheme must be https:// or tcp://.
        /// </summary>
        internal static string CloneCertChainForm_UrlMustBeHttpsOrTcp {
            get {
                return ResourceManager.GetString("CloneCertChainForm_UrlMustBeHttpsOrTcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create proxy script factory.
        /// </summary>
        internal static string ConfigurePacScriptForm_CannotUseProxyScript {
            get {
                return ResourceManager.GetString("ConfigurePacScriptForm_CannotUseProxyScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test returned &apos;{0}&apos;.
        /// </summary>
        internal static string ConfigurePacScriptForm_TestReturned {
            get {
                return ResourceManager.GetString("ConfigurePacScriptForm_TestReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No logged packets available from this connection.
        /// </summary>
        internal static string ConnectionHistoryControl_NoPackets {
            get {
                return ResourceManager.GetString("ConnectionHistoryControl_NoPackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Select.
        /// </summary>
        internal static string CreateCertForm_CertSelect {
            get {
                return ResourceManager.GetString("CreateCertForm_CertSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a certificate from the following list.
        /// </summary>
        internal static string CreateCertForm_CertSelectTitle {
            get {
                return ResourceManager.GetString("CreateCertForm_CertSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a valid RSA key size.
        /// </summary>
        internal static string CreateCertForm_MustSpecifyAValidRSAKeySize {
            get {
                return ResourceManager.GetString("CreateCertForm_MustSpecifyAValidRSAKeySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a root certificate.
        /// </summary>
        internal static string CreateCertForm_MustSpecifyCA {
            get {
                return ResourceManager.GetString("CreateCertForm_MustSpecifyCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a common name.
        /// </summary>
        internal static string CreateCertForm_MustSpecifyCN {
            get {
                return ResourceManager.GetString("CreateCertForm_MustSpecifyCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a template certificate.
        /// </summary>
        internal static string CreateCertForm_MustSpecifyTemplate {
            get {
                return ResourceManager.GetString("CreateCertForm_MustSpecifyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available certificates with private keys found in store.
        /// </summary>
        internal static string CreateCertForm_NoStoreCerts {
            get {
                return ResourceManager.GetString("CreateCertForm_NoStoreCerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate key is protected, do you want to specify the password?.
        /// </summary>
        internal static string CreateCertForm_SpecifyPassword {
            get {
                return ResourceManager.GetString("CreateCertForm_SpecifyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Password?.
        /// </summary>
        internal static string CreateCertForm_SpecifyPasswordCaption {
            get {
                return ResourceManager.GetString("CreateCertForm_SpecifyPasswordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information could not be written out for this certificate..
        /// </summary>
        internal static string CreateCertForm_StoreError {
            get {
                return ResourceManager.GetString("CreateCertForm_StoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide a realm, this identifies the source of the authentication request.
        /// </summary>
        internal static string CredentialsEditorForm_MustProvideARealm {
            get {
                return ResourceManager.GetString("CredentialsEditorForm_MustProvideARealm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide a username.
        /// </summary>
        internal static string CredentialsEditorForm_MustProvideAUsername {
            get {
                return ResourceManager.GetString("CredentialsEditorForm_MustProvideAUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal {0}@{1} already exists, do you want to overwrite the existing one?.
        /// </summary>
        internal static string CredentialsEditorForm_PrincipalAlreadyExists {
            get {
                return ResourceManager.GetString("CredentialsEditorForm_PrincipalAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon CSScriptIcon {
            get {
                object obj = ResourceManager.GetObject("CSScriptIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression to format the node. Access the node through the value property, you can also access the LogPacket directly as &apos;this&apos;. Ignore RawValue when using an expression..
        /// </summary>
        internal static string CustomPacketLogColumn_FormatExpressionDescription {
            get {
                return ResourceManager.GetString("CustomPacketLogColumn_FormatExpressionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return the raw value for the node rather than the node itself, bypasses node formatting.
        /// </summary>
        internal static string CustomPacketLogColumn_RawValueDescription {
            get {
                return ResourceManager.GetString("CustomPacketLogColumn_RawValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the selection path for the part of the frame to display.
        /// </summary>
        internal static string CustomPacketLogColumn_SelectionPathDescription {
            get {
                return ResourceManager.GetString("CustomPacketLogColumn_SelectionPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted String.
        /// </summary>
        internal static string DataKeyEditorControl_FormatStringName {
            get {
                return ResourceManager.GetString("DataKeyEditorControl_FormatStringName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # To use place in an expression using the name, e.g. ExampleScript.RunMe(this)
        ///def RunMe(self):	
        ///    return &quot;Argh!.
        /// </summary>
        internal static string DefaultPythonParserScript {
            get {
                return ResourceManager.GetString("DefaultPythonParserScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node {0} added to right hand side .
        /// </summary>
        internal static string DiffPacketsControl_NodeAdded {
            get {
                return ResourceManager.GetString("DiffPacketsControl_NodeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node {0} deleted from left hand side.
        /// </summary>
        internal static string DiffPacketsControl_NodeDeleted {
            get {
                return ResourceManager.GetString("DiffPacketsControl_NodeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node {0} modified as {1} .
        /// </summary>
        internal static string DiffPacketsControl_NodeModified {
            get {
                return ResourceManager.GetString("DiffPacketsControl_NodeModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No differences found .
        /// </summary>
        internal static string DiffPacketsControl_NoDifferencesFound {
            get {
                return ResourceManager.GetString("DiffPacketsControl_NoDifferencesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No differences.
        /// </summary>
        internal static string DiffPacketsControl_NoDifferencesFoundCaption {
            get {
                return ResourceManager.GetString("DiffPacketsControl_NoDifferencesFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a type for the property.
        /// </summary>
        internal static string EditConfigPropertyForm_SelectAType {
            get {
                return ResourceManager.GetString("EditConfigPropertyForm_SelectAType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid name, it must only contain letters, digits or underscores and must not start with a digit.
        /// </summary>
        internal static string EditConfigPropertyForm_SpecifyAName {
            get {
                return ResourceManager.GetString("EditConfigPropertyForm_SpecifyAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression.
        /// </summary>
        internal static string EditFilterForm_InvalidRegex {
            get {
                return ResourceManager.GetString("EditFilterForm_InvalidRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide a host (* is wildcard).
        /// </summary>
        internal static string EditFilterForm_MustProvideHost {
            get {
                return ResourceManager.GetString("EditFilterForm_MustProvideHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Packet - {0}.
        /// </summary>
        internal static string EditPacketForm_Title {
            get {
                return ResourceManager.GetString("EditPacketForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to clear the log?.
        /// </summary>
        internal static string EventLogControl_ClearLog {
            get {
                return ResourceManager.GetString("EventLogControl_ClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Log?.
        /// </summary>
        internal static string EventLogControl_ClearLogCaption {
            get {
                return ResourceManager.GetString("EventLogControl_ClearLogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files (*.txt)|*.txt|All Files (*.*)|*.*&quot;.
        /// </summary>
        internal static string EventLogControl_TextFilesFilter {
            get {
                return ResourceManager.GetString("EventLogControl_TextFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex string cannot be empty.
        /// </summary>
        internal static string FillBytesForm_EmptyHexString {
            get {
                return ResourceManager.GetString("FillBytesForm_EmptyHexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex string is invalid.
        /// </summary>
        internal static string FillBytesForm_InvalidHexString {
            get {
                return ResourceManager.GetString("FillBytesForm_InvalidHexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex string must be multiples of two characters.
        /// </summary>
        internal static string FillBytesForm_InvalidHexStringLength {
            get {
                return ResourceManager.GetString("FillBytesForm_InvalidHexStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum byte value must be less than maximum.
        /// </summary>
        internal static string FillBytesForm_MinMaxInvalid {
            get {
                return ResourceManager.GetString("FillBytesForm_MinMaxInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string FindPacketForm_CancelButtonText {
            get {
                return ResourceManager.GetString("FindPacketForm_CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string FindPacketForm_FindButtonText {
            get {
                return ResourceManager.GetString("FindPacketForm_FindButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, must specify a matching mode.
        /// </summary>
        internal static string FindPacketForm_SelectMode {
            get {
                return ResourceManager.GetString("FindPacketForm_SelectMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select a mode and an encoding.
        /// </summary>
        internal static string FindPacketForm_SelectModeEncoding {
            get {
                return ResourceManager.GetString("FindPacketForm_SelectModeEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide a search string.
        /// </summary>
        internal static string FindPacketForm_SpecifySearch {
            get {
                return ResourceManager.GetString("FindPacketForm_SpecifySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon FloppyDisk {
            get {
                object obj = ResourceManager.GetObject("FloppyDisk", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon folderopen {
            get {
                object obj = ResourceManager.GetObject("folderopen", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a username.
        /// </summary>
        internal static string GetAuthenticationCredentialsForm_MustSpecifyUsername {
            get {
                return ResourceManager.GetString("GetAuthenticationCredentialsForm_MustSpecifyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Credentials for {0}@{1}.
        /// </summary>
        internal static string GetAuthenticationCredentialsForm_TitleFormat {
            get {
                return ResourceManager.GetString("GetAuthenticationCredentialsForm_TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Number (1 - {0}).
        /// </summary>
        internal static string GotoLineForm_Label {
            get {
                return ResourceManager.GetString("GotoLineForm_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diff Document.
        /// </summary>
        internal static string GuiUtils_CopyToDiffDocument {
            get {
                return ResourceManager.GetString("GuiUtils_CopyToDiffDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet Log.
        /// </summary>
        internal static string GuiUtils_CopyToPacketLog {
            get {
                return ResourceManager.GetString("GuiUtils_CopyToPacketLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Document.
        /// </summary>
        internal static string GuiUtils_CopyToTestDocument {
            get {
                return ResourceManager.GetString("GuiUtils_CopyToTestDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string GuiUtils_LeftDiffDocument {
            get {
                return ResourceManager.GetString("GuiUtils_LeftDiffDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string GuiUtils_NewDocument {
            get {
                return ResourceManager.GetString("GuiUtils_NewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string GuiUtils_RightDiffDocument {
            get {
                return ResourceManager.GetString("GuiUtils_RightDiffDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected data has an invalid base64 length, should be a multiple of 4 bytes..
        /// </summary>
        internal static string HexEditor_InvalidBase64Length {
            get {
                return ResourceManager.GetString("HexEditor_InvalidBase64Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Tags.
        /// </summary>
        internal static string HistogramChartControl_AllTags {
            get {
                return ResourceManager.GetString("HistogramChartControl_AllTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histogram from {0} packet(s), {1} byte(s).
        /// </summary>
        internal static string HistogramChartControl_Title {
            get {
                return ResourceManager.GetString("HistogramChartControl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histogram from {0} packet(s), {1} byte(s).
        /// </summary>
        internal static string HistogramLogViewerForm_Title {
            get {
                return ResourceManager.GetString("HistogramLogViewerForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string InjectPacketControl_CancelButtonText {
            get {
                return ResourceManager.GetString("InjectPacketControl_CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inject.
        /// </summary>
        internal static string InjectPacketControl_InjectButtonText {
            get {
                return ResourceManager.GetString("InjectPacketControl_InjectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not inject at specified node. Not supported.
        /// </summary>
        internal static string InjectPacketForm_NotSupported {
            get {
                return ResourceManager.GetString("InjectPacketForm_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection available for injection.
        /// </summary>
        internal static string InjectPacketForm_SelectGraph {
            get {
                return ResourceManager.GetString("InjectPacketForm_SelectGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No node selected for injection.
        /// </summary>
        internal static string InjectPacketForm_SelectNode {
            get {
                return ResourceManager.GetString("InjectPacketForm_SelectNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripted Layer.
        /// </summary>
        internal static string LayerEditorControl_ScriptMenuItem {
            get {
                return ResourceManager.GetString("LayerEditorControl_ScriptMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The label to assign to the line. Allows a node to specify which route a packet should take.
        /// </summary>
        internal static string LineContainer_LabelDescription {
            get {
                return ResourceManager.GetString("LineContainer_LabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if this path only holds a weak reference to the destination node. If true it does not block shutdown of destination.
        /// </summary>
        internal static string LineContainer_WeakDescription {
            get {
                return ResourceManager.GetString("LineContainer_WeakDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFX Certificate (*.pfx;*.p12)|*.pfx;*.p12|Certificate Files (*.cer,*.pem,*.crt,*.der)|*.cer;*.pem;*.crt;*.der|All Files (*.*)|*.*.
        /// </summary>
        internal static string LoadCertFromFileForm_CertFilter {
            get {
                return ResourceManager.GetString("LoadCertFromFileForm_CertFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load private key from file.
        /// </summary>
        internal static string LoadCertFromFileForm_InvalidPrivateKeyFile {
            get {
                return ResourceManager.GetString("LoadCertFromFileForm_InvalidPrivateKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key File (*.key)|*.key|All Files (*.*)|*.*.
        /// </summary>
        internal static string LoadCertFromFileForm_KeyFilter {
            get {
                return ResourceManager.GetString("LoadCertFromFileForm_KeyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate does not have a private key.
        /// </summary>
        internal static string LoadCertFromFileForm_NoPrivateKey {
            get {
                return ResourceManager.GetString("LoadCertFromFileForm_NoPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a certificate file.
        /// </summary>
        internal static string LoadCertFromFileForm_SpecifyCert {
            get {
                return ResourceManager.GetString("LoadCertFromFileForm_SpecifyCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a key file.
        /// </summary>
        internal static string LoadCertFromFileForm_SpecifyKey {
            get {
                return ResourceManager.GetString("LoadCertFromFileForm_SpecifyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBox_ErrorString {
            get {
                return ResourceManager.GetString("MessageBox_ErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No document set in node, do you want to create a new document?.
        /// </summary>
        internal static string NetGraphDocumentControl_NoDocumentSet {
            get {
                return ResourceManager.GetString("NetGraphDocumentControl_NoDocumentSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Document?.
        /// </summary>
        internal static string NetGraphDocumentControl_NoDocumentSetCaption {
            get {
                return ResourceManager.GetString("NetGraphDocumentControl_NoDocumentSetCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon NetGraphIcon {
            get {
                object obj = ResourceManager.GetObject("NetGraphIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Network {
            get {
                object obj = ResourceManager.GetObject("Network", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Network_Map {
            get {
                object obj = ResourceManager.GetObject("Network_Map", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Network_Map_Started {
            get {
                object obj = ResourceManager.GetObject("Network_Map_Started", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon otheroptions {
            get {
                object obj = ResourceManager.GetObject("otheroptions", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width of the column.
        /// </summary>
        internal static string PacketLogColumn_ColumnWidthDescription {
            get {
                return ResourceManager.GetString("PacketLogColumn_ColumnWidthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET style custom format string for value, must be of the form {0:fmt}, see String.Format in MSDN for more information.
        /// </summary>
        internal static string PacketLogColumn_CustomFormatDescription {
            get {
                return ResourceManager.GetString("PacketLogColumn_CustomFormatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the column.
        /// </summary>
        internal static string PacketLogColumn_NameDescription {
            get {
                return ResourceManager.GetString("PacketLogColumn_NameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to clear the log?.
        /// </summary>
        internal static string PacketLogControl_ClearLog {
            get {
                return ResourceManager.GetString("PacketLogControl_ClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Log?.
        /// </summary>
        internal static string PacketLogControl_ClearLogCaption {
            get {
                return ResourceManager.GetString("PacketLogControl_ClearLogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet Log Column Editor.
        /// </summary>
        internal static string PacketLogControl_ColumnEditor {
            get {
                return ResourceManager.GetString("PacketLogControl_ColumnEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To {0} Left.
        /// </summary>
        internal static string PacketLogControl_CopyToExistingDiffLogLeft {
            get {
                return ResourceManager.GetString("PacketLogControl_CopyToExistingDiffLogLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To {0} Right.
        /// </summary>
        internal static string PacketLogControl_CopyToExistingDiffLogRight {
            get {
                return ResourceManager.GetString("PacketLogControl_CopyToExistingDiffLogRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Diff Log Left.
        /// </summary>
        internal static string PacketLogControl_CopyToNewDiffLogLeft {
            get {
                return ResourceManager.GetString("PacketLogControl_CopyToNewDiffLogLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Diff Log Right.
        /// </summary>
        internal static string PacketLogControl_CopyToNewDiffLogRight {
            get {
                return ResourceManager.GetString("PacketLogControl_CopyToNewDiffLogRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string PacketLogControl_CustomColumn {
            get {
                return ResourceManager.GetString("PacketLogControl_CustomColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string PacketLogControl_DataColumn {
            get {
                return ResourceManager.GetString("PacketLogControl_DataColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading file {0}.
        /// </summary>
        internal static string PacketLogControl_ErrorReadingFile {
            get {
                return ResourceManager.GetString("PacketLogControl_ErrorReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing packets &apos;{0}&apos;.
        /// </summary>
        internal static string PacketLogControl_ErrorWritingPackets {
            get {
                return ResourceManager.GetString("PacketLogControl_ErrorWritingPackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash.
        /// </summary>
        internal static string PacketLogControl_HashColumn {
            get {
                return ResourceManager.GetString("PacketLogControl_HashColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string PacketLogControl_LengthColumn {
            get {
                return ResourceManager.GetString("PacketLogControl_LengthColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string PacketLogControl_NetworkColumn {
            get {
                return ResourceManager.GetString("PacketLogControl_NetworkColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string PacketLogControl_NoColumn {
            get {
                return ResourceManager.GetString("PacketLogControl_NoColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select two packets to difference.
        /// </summary>
        internal static string PacketLogControl_SelectDiffPackets {
            get {
                return ResourceManager.GetString("PacketLogControl_SelectDiffPackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string PacketLogControl_TagColumn {
            get {
                return ResourceManager.GetString("PacketLogControl_TagColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string PacketLogControl_TimestampColumn {
            get {
                return ResourceManager.GetString("PacketLogControl_TimestampColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log contains modified data, do you want to save now?.
        /// </summary>
        internal static string PacketLogViewerForm_ConfirmSave {
            get {
                return ResourceManager.GetString("PacketLogViewerForm_ConfirmSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save?.
        /// </summary>
        internal static string PacketLogViewerForm_ConfirmSaveCaption {
            get {
                return ResourceManager.GetString("PacketLogViewerForm_ConfirmSaveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to convert this packet to bytes?.
        /// </summary>
        internal static string PacketLogViewerForm_ConvertToBytes {
            get {
                return ResourceManager.GetString("PacketLogViewerForm_ConvertToBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert?.
        /// </summary>
        internal static string PacketLogViewerForm_ConvertToBytesCaption {
            get {
                return ResourceManager.GetString("PacketLogViewerForm_ConvertToBytesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} - {2} - {3} - {4}.
        /// </summary>
        internal static string PacketLogViewerForm_Header {
            get {
                return ResourceManager.GetString("PacketLogViewerForm_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet Log.
        /// </summary>
        internal static string PacketLogViewerForm_Title {
            get {
                return ResourceManager.GetString("PacketLogViewerForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet Log - Read Only.
        /// </summary>
        internal static string PacketLogViewerForm_TitleReadOnly {
            get {
                return ResourceManager.GetString("PacketLogViewerForm_TitleReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ParserComponent {
            get {
                object obj = ResourceManager.GetObject("ParserComponent", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# Source File (*.cs)|*.cs|All Files (*.*)|*.*.
        /// </summary>
        internal static string ParserDocumentControl_CSSourceFilter {
            get {
                return ResourceManager.GetString("ParserDocumentControl_CSSourceFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enums.
        /// </summary>
        internal static string ParserDocumentControl_EnumsNodeName {
            get {
                return ResourceManager.GetString("ParserDocumentControl_EnumsNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &apos;{0}&apos; is not a valid identifier.
        /// </summary>
        internal static string ParserDocumentControl_InvalidIdentifier {
            get {
                return ResourceManager.GetString("ParserDocumentControl_InvalidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name.
        /// </summary>
        internal static string ParserDocumentControl_InvalidIdentifierCaption {
            get {
                return ResourceManager.GetString("ParserDocumentControl_InvalidIdentifierCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parser type.
        /// </summary>
        internal static string ParserDocumentControl_InvalidParserType {
            get {
                return ResourceManager.GetString("ParserDocumentControl_InvalidParserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsers.
        /// </summary>
        internal static string ParserDocumentControl_ParsersNodeName {
            get {
                return ResourceManager.GetString("ParserDocumentControl_ParsersNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove {0}?.
        /// </summary>
        internal static string ParserDocumentControl_RemoveType {
            get {
                return ResourceManager.GetString("ParserDocumentControl_RemoveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove {0}?.
        /// </summary>
        internal static string ParserDocumentControl_RemoveTypeCaption {
            get {
                return ResourceManager.GetString("ParserDocumentControl_RemoveTypeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string ParserDocumentControl_RootNodeName {
            get {
                return ResourceManager.GetString("ParserDocumentControl_RootNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripts.
        /// </summary>
        internal static string ParserDocumentControl_ScriptsNodeName {
            get {
                return ResourceManager.GetString("ParserDocumentControl_ScriptsNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequences.
        /// </summary>
        internal static string ParserDocumentControl_SequencesNodeName {
            get {
                return ResourceManager.GetString("ParserDocumentControl_SequencesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} already exists, please choose a different name.
        /// </summary>
        internal static string ParserDocumentControl_TypeNameExists {
            get {
                return ResourceManager.GetString("ParserDocumentControl_TypeNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name exists.
        /// </summary>
        internal static string ParserDocumentControl_TypeNameExistsCaption {
            get {
                return ResourceManager.GetString("ParserDocumentControl_TypeNameExistsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parser validated ok.
        /// </summary>
        internal static string ParserDocumentControl_Validation {
            get {
                return ResourceManager.GetString("ParserDocumentControl_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Passed.
        /// </summary>
        internal static string ParserDocumentControl_ValidationCaption {
            get {
                return ResourceManager.GetString("ParserDocumentControl_ValidationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        internal static string ParserDocumentControl_ValidationError {
            get {
                return ResourceManager.GetString("ParserDocumentControl_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCAP Files (*.pcap)|*.pcap|All Files (*.*)|*.*.
        /// </summary>
        internal static string PCAPFileFilter_String {
            get {
                return ResourceManager.GetString("PCAPFileFilter_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value - {0}.
        /// </summary>
        internal static string PrimitiveValueEditorForm_InvalidValue {
            get {
                return ResourceManager.GetString("PrimitiveValueEditorForm_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemblies (*.dll;*.exe)|*.dll;*.exe|All Files (*.*)|*.*.
        /// </summary>
        internal static string ProjectExplorer_AssembliesFileFilter {
            get {
                return ResourceManager.GetString("ProjectExplorer_AssembliesFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create test type.
        /// </summary>
        internal static string ProjectExplorer_CouldntCreateTest {
            get {
                return ResourceManager.GetString("ProjectExplorer_CouldntCreateTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string ProjectExplorer_DataNodeName {
            get {
                return ResourceManager.GetString("ProjectExplorer_DataNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete document &apos;{0}&apos;?.
        /// </summary>
        internal static string ProjectExplorer_DeleteDocument {
            get {
                return ResourceManager.GetString("ProjectExplorer_DeleteDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete?.
        /// </summary>
        internal static string ProjectExplorer_DeleteDocumentCaption {
            get {
                return ResourceManager.GetString("ProjectExplorer_DeleteDocumentCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphs.
        /// </summary>
        internal static string ProjectExplorer_GraphsNodeName {
            get {
                return ResourceManager.GetString("ProjectExplorer_GraphsNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string ProjectExplorer_RootNodeName {
            get {
                return ResourceManager.GetString("ProjectExplorer_RootNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripts.
        /// </summary>
        internal static string ProjectExplorer_ScriptsNodeName {
            get {
                return ResourceManager.GetString("ProjectExplorer_ScriptsNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string ProjectExplorer_ServicesNodeName {
            get {
                return ResourceManager.GetString("ProjectExplorer_ServicesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Test.
        /// </summary>
        internal static string ProjectExplorer_TestName {
            get {
                return ResourceManager.GetString("ProjectExplorer_TestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests.
        /// </summary>
        internal static string ProjectExplorer_TestsNodeName {
            get {
                return ResourceManager.GetString("ProjectExplorer_TestsNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PythonScriptIcon {
            get {
                object obj = ResourceManager.GetObject("PythonScriptIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SyntaxDefinition name=&quot;Python&quot; extensions=&quot;.py&quot;&gt;
        ///	
        ///	&lt;Properties&gt;
        ///		&lt;Property name=&quot;LineComment&quot; value=&quot;#&quot;/&gt;
        ///	&lt;/Properties&gt;
        ///	
        ///	&lt;Digits name=&quot;Digits&quot; color=&quot;DarkBlue&quot;/&gt;
        ///
        ///	&lt;RuleSets&gt;
        ///		&lt;RuleSet ignorecase=&quot;false&quot;&gt;
        ///			
        ///			&lt;Delimiters&gt;()[]{}@,:.`=;+-*/% &amp;amp;|^&amp;gt;&amp;lt;&lt;/Delimiters&gt;
        ///			
        ///			&lt;Span name=&quot;DocComment&quot; color=&quot;Green&quot;&gt;
        ///				&lt;Begin&gt;&quot;&quot;&quot;&lt;/Begin&gt;
        ///				&lt;End&gt;&quot;&quot;&quot;&lt;/End&gt;
        ///			&lt;/Span&gt;
        ///			
        ///			&lt;Span name=&quot;SingleQuoteDocComment&quot; color=&quot;Green&quot;&gt;
        ///				&lt;Begin&gt;&apos;&apos;&apos;&lt;/Begin&gt;
        ///				&lt;End&gt;&apos;&apos;&apos;&lt;/End&gt;
        ///			&lt;/Span&gt;
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PythonSyntaxHighlighting {
            get {
                return ResourceManager.GetString("PythonSyntaxHighlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a match.
        /// </summary>
        internal static string ScriptDocumentControl_NoMatch {
            get {
                return ResourceManager.GetString("ScriptDocumentControl_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Match.
        /// </summary>
        internal static string ScriptDocumentControl_NoMatchCaption {
            get {
                return ResourceManager.GetString("ScriptDocumentControl_NoMatchCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script did not parse correctly, do you want to continue to save?.
        /// </summary>
        internal static string ScriptDocumentControl_ParseFailedSaveScript {
            get {
                return ResourceManager.GetString("ScriptDocumentControl_ParseFailedSaveScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save your script?.
        /// </summary>
        internal static string ScriptDocumentControl_SaveScript {
            get {
                return ResourceManager.GetString("ScriptDocumentControl_SaveScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0}?.
        /// </summary>
        internal static string ScriptDocumentControl_SaveScriptCaption {
            get {
                return ResourceManager.GetString("ScriptDocumentControl_SaveScriptCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script OK.
        /// </summary>
        internal static string ScriptDocumentControl_ScriptOk {
            get {
                return ResourceManager.GetString("ScriptDocumentControl_ScriptOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ScriptDocumentControl_ScriptOkCaption {
            get {
                return ResourceManager.GetString("ScriptDocumentControl_ScriptOkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Source Files (*.{1})|*.{1}|{2}.
        /// </summary>
        internal static string ScriptDocumentControl_SourceFilter {
            get {
                return ResourceManager.GetString("ScriptDocumentControl_SourceFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ScriptIcon {
            get {
                object obj = ResourceManager.GetObject("ScriptIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ScriptSelectForm_Caption {
            get {
                return ResourceManager.GetString("ScriptSelectForm_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a class.
        /// </summary>
        internal static string ScriptSelectForm_NoClass {
            get {
                return ResourceManager.GetString("ScriptSelectForm_NoClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a script document.
        /// </summary>
        internal static string ScriptSelectForm_NoDocument {
            get {
                return ResourceManager.GetString("ScriptSelectForm_NoDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end offset must be greater or equal to start offset.
        /// </summary>
        internal static string SelectBlockForm_EndOffsetLessThanOffset {
            get {
                return ResourceManager.GetString("SelectBlockForm_EndOffsetLessThanOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The offset must be less than the size of the hex ({0} bytes).
        /// </summary>
        internal static string SelectBlockForm_OffsetGreaterThanSize {
            get {
                return ResourceManager.GetString("SelectBlockForm_OffsetGreaterThanSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select a template.
        /// </summary>
        internal static string SelectEndointForm_SelectServer {
            get {
                return ResourceManager.GetString("SelectEndointForm_SelectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a class.
        /// </summary>
        internal static string SelectEndpointForm_SelectClass {
            get {
                return ResourceManager.GetString("SelectEndpointForm_SelectClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a script document.
        /// </summary>
        internal static string SelectEndpointForm_SelectScript {
            get {
                return ResourceManager.GetString("SelectEndpointForm_SelectScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string SelectLibraryNodeForm_DescriptionColumn {
            get {
                return ResourceManager.GetString("SelectLibraryNodeForm_DescriptionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SelectLibraryNodeForm_NameColumn {
            get {
                return ResourceManager.GetString("SelectLibraryNodeForm_NameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select a node type.
        /// </summary>
        internal static string SelectLibraryNodeForm_SelectNode {
            get {
                return ResourceManager.GetString("SelectLibraryNodeForm_SelectNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string SelectScriptTemplateForm_EmptyScript {
            get {
                return ResourceManager.GetString("SelectScriptTemplateForm_EmptyScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty script file.
        /// </summary>
        internal static string SelectScriptTemplateForm_EmptyScriptDescription {
            get {
                return ResourceManager.GetString("SelectScriptTemplateForm_EmptyScriptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string SelectTemplateForm_DescriptionColumn {
            get {
                return ResourceManager.GetString("SelectTemplateForm_DescriptionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SelectTemplateForm_NameColumn {
            get {
                return ResourceManager.GetString("SelectTemplateForm_NameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select a template type.
        /// </summary>
        internal static string SelectTemplateForm_SpecifyTemplate {
            get {
                return ResourceManager.GetString("SelectTemplateForm_SpecifyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame was modified, do you want to save it?.
        /// </summary>
        internal static string SingleFrameEditorControl_FrameModifiedSave {
            get {
                return ResourceManager.GetString("SingleFrameEditorControl_FrameModifiedSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Frame?.
        /// </summary>
        internal static string SingleFrameEditorControl_FrameModifiedSaveCaption {
            get {
                return ResourceManager.GetString("SingleFrameEditorControl_FrameModifiedSaveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading certificate from store: {0}.
        /// </summary>
        internal static string SslConfigControl_ErrorLoadingStoreCert {
            get {
                return ResourceManager.GetString("SslConfigControl_ErrorLoadingStoreCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available certificates with private keys found in store.
        /// </summary>
        internal static string SslConfigControl_NoPrivateKeyInStore {
            get {
                return ResourceManager.GetString("SslConfigControl_NoPrivateKeyInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a certificate with a private key.
        /// </summary>
        internal static string SslConfigControl_SpecifyCertPrivateKey {
            get {
                return ResourceManager.GetString("SslConfigControl_SpecifyCertPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set State {0}.
        /// </summary>
        internal static string StateGraphDocumentControl_SetStateName {
            get {
                return ResourceManager.GetString("StateGraphDocumentControl_SetStateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex string must be a multiple of 2 hex characters.
        /// </summary>
        internal static string StringConverters_InvalidHexStringLength {
            get {
                return ResourceManager.GetString("StringConverters_InvalidHexStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Bytes: #VAL.
        /// </summary>
        internal static string TagStatisticsChartControl_ByteCountToolTip {
            get {
                return ResourceManager.GetString("TagStatisticsChartControl_ByteCountToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Packets: #VAL.
        /// </summary>
        internal static string TagStatisticsChartControl_CountToolTip {
            get {
                return ResourceManager.GetString("TagStatisticsChartControl_CountToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon textdoc {
            get {
                object obj = ResourceManager.GetObject("textdoc", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files (*.txt)|*.txt|All Files (*.*)|*.*.
        /// </summary>
        internal static string TextFileFilter_String {
            get {
                return ResourceManager.GetString("TextFileFilter_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return the ticks in 100ns intervals rather than the full date time.
        /// </summary>
        internal static string TimestampPacketLogColumn_TicksDescription {
            get {
                return ResourceManager.GetString("TimestampPacketLogColumn_TicksDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a match.
        /// </summary>
        internal static string TreeDataKeyEditorControl_NoMatch {
            get {
                return ResourceManager.GetString("TreeDataKeyEditorControl_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Match.
        /// </summary>
        internal static string TreeDataKeyEditorControl_NoMatchCaption {
            get {
                return ResourceManager.GetString("TreeDataKeyEditorControl_NoMatchCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results returned from parse with.
        /// </summary>
        internal static string TreeDataKeyEditorControl_NoParseResults {
            get {
                return ResourceManager.GetString("TreeDataKeyEditorControl_NoParseResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        internal static string TreeDataKeyEditorControl_NoParseResultsCaption {
            get {
                return ResourceManager.GetString("TreeDataKeyEditorControl_NoParseResultsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse Error.
        /// </summary>
        internal static string TreeDataKeyEditorControl_ParseError {
            get {
                return ResourceManager.GetString("TreeDataKeyEditorControl_ParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon UtilityText {
            get {
                object obj = ResourceManager.GetObject("UtilityText", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon VBScriptIcon {
            get {
                object obj = ResourceManager.GetObject("VBScriptIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon VSProject_genericproject {
            get {
                object obj = ResourceManager.GetObject("VSProject_genericproject", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
