//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CANAPE.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CANAPE.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get a certificate when the match is null.
        /// </summary>
        internal static string CertManager_NullMatch {
            get {
                return ResourceManager.GetString("CertManager_NullMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network: {0}, Id: {1}, StartTime: {2}, EndTime: {3}.
        /// </summary>
        internal static string ConnectionHistoryEntry_ToString {
            get {
                return ResourceManager.GetString("ConnectionHistoryEntry_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Proxy Server.
        /// </summary>
        internal static string FixedProxyServer_ToString {
            get {
                return ResourceManager.GetString("FixedProxyServer_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Proxy-Authorization header received.
        /// </summary>
        internal static string FullHttpProxyServer_InvalidAuthLine {
            get {
                return ResourceManager.GetString("FullHttpProxyServer_InvalidAuthLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid base64 in authentication header.
        /// </summary>
        internal static string FullHttpProxyServer_InvalidBase64Auth {
            get {
                return ResourceManager.GetString("FullHttpProxyServer_InvalidBase64Auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username:password string in basic authentication header.
        /// </summary>
        internal static string FullHttpProxyServer_InvalidUsernamePasswordString {
            get {
                return ResourceManager.GetString("FullHttpProxyServer_InvalidUsernamePasswordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only support basic authentication for proxy.
        /// </summary>
        internal static string FullHttpProxyServer_OnlySupportBasicAuth {
            get {
                return ResourceManager.GetString("FullHttpProxyServer_OnlySupportBasicAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse response as no HTTP request was made.
        /// </summary>
        internal static string HttpNetworkLayer_CannotParserResponseNotRequestMade {
            get {
                return ResourceManager.GetString("HttpNetworkLayer_CannotParserResponseNotRequestMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP proxy server sent error {0} in response to CONNECT {1}:{2}.
        /// </summary>
        internal static string HttpProxyClient_ErrorOnConnect {
            get {
                return ResourceManager.GetString("HttpProxyClient_ErrorOnConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reconnecting to HTTP proxy.
        /// </summary>
        internal static string HttpProxyClient_ErrorReconnecting {
            get {
                return ResourceManager.GetString("HttpProxyClient_ErrorReconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid proxy token passed.
        /// </summary>
        internal static string HttpProxyClient_InvalidProxyToken {
            get {
                return ResourceManager.GetString("HttpProxyClient_InvalidProxyToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid response from HTTP proxy.
        /// </summary>
        internal static string HttpProxyClient_InvalidResponse {
            get {
                return ResourceManager.GetString("HttpProxyClient_InvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server sent no response.
        /// </summary>
        internal static string HttpProxyClient_NoResponse {
            get {
                return ResourceManager.GetString("HttpProxyClient_NoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid HTTP CONNECT port &apos;{0}&apos;.
        /// </summary>
        internal static string HttpProxyServer_InvalidConnect {
            get {
                return ResourceManager.GetString("HttpProxyServer_InvalidConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid HTTP proxy request &apos;{0}&apos;.
        /// </summary>
        internal static string HttpProxyServer_InvalidRequest {
            get {
                return ResourceManager.GetString("HttpProxyServer_InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL passed for HTTP request &apos;{0}&apos;.
        /// </summary>
        internal static string HttpProxyServer_InvalidUrl {
            get {
                return ResourceManager.GetString("HttpProxyServer_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Proxy Server.
        /// </summary>
        internal static string HttpProxyServer_ToString {
            get {
                return ResourceManager.GetString("HttpProxyServer_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string IpNetworkListener_ToStringFormat {
            get {
                return ResourceManager.GetString("IpNetworkListener_ToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid client type in proxy token.
        /// </summary>
        internal static string IpProxyClient_InvalidTokenType {
            get {
                return ResourceManager.GetString("IpProxyClient_InvalidTokenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address = {0}, Port = {1}.
        /// </summary>
        internal static string IpProxyFilter_ToString {
            get {
                return ResourceManager.GetString("IpProxyFilter_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subgraph must have a client and server node.
        /// </summary>
        internal static string LayerSectionNode_InvalidGraph {
            get {
                return ResourceManager.GetString("LayerSectionNode_InvalidGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous Listener.
        /// </summary>
        internal static string ManualNetworkListener_Anonymous {
            get {
                return ResourceManager.GetString("ManualNetworkListener_Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created new manual connection.
        /// </summary>
        internal static string ManualNetworkListener_CreateLogString {
            get {
                return ResourceManager.GetString("ManualNetworkListener_CreateLogString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one server node in graph.
        /// </summary>
        internal static string NetworkServerService_MultipleServerNodes {
            get {
                return ResourceManager.GetString("NetworkServerService_MultipleServerNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No server node specified.
        /// </summary>
        internal static string NetworkServerService_NoServerNode {
            get {
                return ResourceManager.GetString("NetworkServerService_NoServerNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection {0} closed.
        /// </summary>
        internal static string NetworkServiceBase_ConnectionClosed {
            get {
                return ResourceManager.GetString("NetworkServiceBase_ConnectionClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection {0} established.
        /// </summary>
        internal static string NetworkServiceBase_ConnectionEstablished {
            get {
                return ResourceManager.GetString("NetworkServiceBase_ConnectionEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start service.
        /// </summary>
        internal static string NetworkServiceBase_CouldNotStartService {
            get {
                return ResourceManager.GetString("NetworkServiceBase_CouldNotStartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy connection was filtered.
        /// </summary>
        internal static string ProxyNetworkService_ConnectionFiltered {
            get {
                return ResourceManager.GetString("ProxyNetworkService_ConnectionFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need at least 1 client and 1 server node to start a connection.
        /// </summary>
        internal static string ProxyNetworkService_InvalidGraph {
            get {
                return ResourceManager.GetString("ProxyNetworkService_InvalidGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched on filter {0}.
        /// </summary>
        internal static string ProxyNetworkService_MatchedFilter {
            get {
                return ResourceManager.GetString("ProxyNetworkService_MatchedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listener ({0}), Server ({1}).
        /// </summary>
        internal static string ProxyNetworkService_ToStringFormat {
            get {
                return ResourceManager.GetString("ProxyNetworkService_ToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Reverse Proxy Server.
        /// </summary>
        internal static string ReverseHttpProxyServer_ToString {
            get {
                return ResourceManager.GetString("ReverseHttpProxyServer_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid system proxy string {0}.
        /// </summary>
        internal static string ScriptProxyClient_InvalidServer {
            get {
                return ResourceManager.GetString("ScriptProxyClient_InvalidServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token type.
        /// </summary>
        internal static string ScriptProxyClient_InvalidToken {
            get {
                return ResourceManager.GetString("ScriptProxyClient_InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid system proxy type {0}.
        /// </summary>
        internal static string ScriptProxyClient_InvalidType {
            get {
                return ResourceManager.GetString("ScriptProxyClient_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy script returned &apos;{0}&apos; for URL &apos;{1}&apos;.
        /// </summary>
        internal static string ScriptProxyClient_ScriptReturned {
            get {
                return ResourceManager.GetString("ScriptProxyClient_ScriptReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find address for host.
        /// </summary>
        internal static string SocksProxyClient_CouldNotGetHost {
            get {
                return ResourceManager.GetString("SocksProxyClient_CouldNotGetHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of stream while reading domain length.
        /// </summary>
        internal static string SocksProxyClient_EosInDomain {
            get {
                return ResourceManager.GetString("SocksProxyClient_EosInDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid address type, cannot read out rest of SOCKS data.
        /// </summary>
        internal static string SocksProxyClient_InvalidAddrType {
            get {
                return ResourceManager.GetString("SocksProxyClient_InvalidAddrType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid proxy token passed, address is not v4 or v6.
        /// </summary>
        internal static string SocksProxyClient_InvalidProxyToken {
            get {
                return ResourceManager.GetString("SocksProxyClient_InvalidProxyToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid proxy token passed, cannot send any connection details.
        /// </summary>
        internal static string SocksProxyClient_InvalidProxyToken2 {
            get {
                return ResourceManager.GetString("SocksProxyClient_InvalidProxyToken2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid proxy token passed.
        /// </summary>
        internal static string SocksProxyClient_InvalidProxyToken3 {
            get {
                return ResourceManager.GetString("SocksProxyClient_InvalidProxyToken3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received invalid response from SOCKSv5 server.
        /// </summary>
        internal static string SocksProxyClient_InvalidV5Response {
            get {
                return ResourceManager.GetString("SocksProxyClient_InvalidV5Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received invalid response from SOCKSv5 server {0:X}/{1:X}.
        /// </summary>
        internal static string SocksProxyClient_InvalidV5Response2 {
            get {
                return ResourceManager.GetString("SocksProxyClient_InvalidV5Response2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsSupported said we supporting this version but it isn&apos;t one we do.
        /// </summary>
        internal static string SocksProxyServer_IsSupportedError {
            get {
                return ResourceManager.GetString("SocksProxyServer_IsSupportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SocksProxy: New SOCKS v4 connection.
        /// </summary>
        internal static string SocksProxyServer_NewV4ConnectionLog {
            get {
                return ResourceManager.GetString("SocksProxyServer_NewV4ConnectionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SocksProxy: New SOCKS v5 connection.
        /// </summary>
        internal static string SocksProxyServer_NewV5ConnectionLog {
            get {
                return ResourceManager.GetString("SocksProxyServer_NewV5ConnectionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCKS Proxy Server.
        /// </summary>
        internal static string SocksProxyServer_ToString {
            get {
                return ResourceManager.GetString("SocksProxyServer_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported SOCKS version in token &apos;{0}&apos;.
        /// </summary>
        internal static string SocksProxyServer_UnsupportedTokenVersion {
            get {
                return ResourceManager.GetString("SocksProxyServer_UnsupportedTokenVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported SOCKS version &apos;{0}&apos;.
        /// </summary>
        internal static string SocksProxyServer_UnsupportedVersionLog {
            get {
                return ResourceManager.GetString("SocksProxyServer_UnsupportedVersionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCKv4a protocol used.
        /// </summary>
        internal static string SocksProxyServer_V4AUsed {
            get {
                return ResourceManager.GetString("SocksProxyServer_V4AUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCKSv4 connection to {0}:{1}.
        /// </summary>
        internal static string SocksProxyServer_V4ConnectionLog {
            get {
                return ResourceManager.GetString("SocksProxyServer_V4ConnectionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCKSv5 connection to {0}:{1}.
        /// </summary>
        internal static string SocksProxyServer_V5ConnectionLog {
            get {
                return ResourceManager.GetString("SocksProxyServer_V5ConnectionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get server certificate.
        /// </summary>
        internal static string SslNetworkLayer_CannotGetServerCertificate {
            get {
                return ResourceManager.GetString("SslNetworkLayer_CannotGetServerCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to SSL server with Protocol {0} Subject &apos;{1}&apos; IsSigned {2} IsMutuallyAuthenticated {3} IsEncrypted {4}.
        /// </summary>
        internal static string SslNetworkLayer_ClientConnectLog {
            get {
                return ResourceManager.GetString("SslNetworkLayer_ClientConnectLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected SSL client with Protocol {0} IsSigned {1} IsMutuallyAuthenticated {2} IsEncrypted {3}.
        /// </summary>
        internal static string SslNetworkLayer_ClientLogString {
            get {
                return ResourceManager.GetString("SslNetworkLayer_ClientLogString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL Layer: Enabled {0}.
        /// </summary>
        internal static string SslNetworkLayerConfig_ToString {
            get {
                return ResourceManager.GetString("SslNetworkLayerConfig_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP listener bound to {0}.
        /// </summary>
        internal static string TcpNetworkListener_AutoBind {
            get {
                return ResourceManager.GetString("TcpNetworkListener_AutoBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection received from {0}.
        /// </summary>
        internal static string TcpNetworkListener_ConnectionLogString {
            get {
                return ResourceManager.GetString("TcpNetworkListener_ConnectionLogString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP listener bound to {0}.
        /// </summary>
        internal static string UdpNetworkListener_AutoBind {
            get {
                return ResourceManager.GetString("UdpNetworkListener_AutoBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection received from {0}.
        /// </summary>
        internal static string UdpNetworkListener_ConnectionLogString {
            get {
                return ResourceManager.GetString("UdpNetworkListener_ConnectionLogString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No UDP connection available.
        /// </summary>
        internal static string UdpNetworkListener_NoUdpConnection {
            get {
                return ResourceManager.GetString("UdpNetworkListener_NoUdpConnection", resourceCulture);
            }
        }
    }
}
